import {
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  Check,
  CornerDownLeft,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  Disc3,
  Download,
  ExternalLink,
  Heart,
  Info,
  ListMusic,
  Loader,
  Minus,
  Music,
  Pause,
  Pencil,
  Play,
  Plus,
  RefreshCw,
  Search,
  Settings,
  Trash2,
  Upload,
  User,
  Users,
  X,
} from "@lucide/svelte";
import type { Component } from "svelte";

// The icon set, by name. New code draws icons as `<Icon name="search" />` and
// never imports the library itself, so the set can be swapped for a drawn one
// by changing this map and nothing else. Lucide is the set until then.
// A name missing here is added here, next to the rest.
export const icons = {
  "arrow-down": ArrowDown,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up": ArrowUp,
  "arrow-up-right": ArrowUpRight,
  check: Check,
  enter: CornerDownLeft,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  alert: CircleAlert,
  release: Disc3,
  download: Download,
  external: ExternalLink,
  heart: Heart,
  info: Info,
  playlist: ListMusic,
  busy: Loader,
  minus: Minus,
  track: Music,
  pause: Pause,
  edit: Pencil,
  play: Play,
  plus: Plus,
  refresh: RefreshCw,
  search: Search,
  settings: Settings,
  delete: Trash2,
  upload: Upload,
  artist: User,
  artists: Users,
  close: X,
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
} satisfies Record<string, Component<any>>;

export type IconName = keyof typeof icons;
