// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: app_tokens.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appTokenByHash = `-- name: AppTokenByHash :one
SELECT id, name, revoked_at
FROM app_tokens
WHERE token_hash = $1
`

type AppTokenByHashRow struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

// The token a request presented, revoked or not. A revoked one is read rather
// than filtered out so the middleware can tell a withdrawn phone from a token
// nothing ever issued; both are refused, and only one of them is worth a log
// line.
func (q *Queries) AppTokenByHash(ctx context.Context, tokenHash []byte) (AppTokenByHashRow, error) {
	row := q.db.QueryRow(ctx, appTokenByHash, tokenHash)
	var i AppTokenByHashRow
	err := row.Scan(&i.ID, &i.Name, &i.RevokedAt)
	return i, err
}

const createAppToken = `-- name: CreateAppToken :one
INSERT INTO app_tokens (name, token_hash, created_by)
VALUES (
    $1,
    $2,
    $3
)
RETURNING id, name, created_by, created_at, last_used_at
`

type CreateAppTokenParams struct {
	Name      string `json:"name"`
	TokenHash []byte `json:"token_hash"`
	CreatedBy string `json:"created_by"`
}

type CreateAppTokenRow struct {
	ID         uuid.UUID          `json:"id"`
	Name       string             `json:"name"`
	CreatedBy  string             `json:"created_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}

// Mint a token for one phone. The hash arrives already computed; the plain
// token never reaches the database.
func (q *Queries) CreateAppToken(ctx context.Context, arg CreateAppTokenParams) (CreateAppTokenRow, error) {
	row := q.db.QueryRow(ctx, createAppToken, arg.Name, arg.TokenHash, arg.CreatedBy)
	var i CreateAppTokenRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const listAppTokens = `-- name: ListAppTokens :many
SELECT id, name, created_by, created_at, last_used_at
FROM app_tokens
WHERE revoked_at IS NULL
ORDER BY created_at DESC
`

type ListAppTokensRow struct {
	ID         uuid.UUID          `json:"id"`
	Name       string             `json:"name"`
	CreatedBy  string             `json:"created_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}

// The phones Settings shows. Revoked rows are kept in the table and are not a
// phone any more, so they are not listed.
func (q *Queries) ListAppTokens(ctx context.Context) ([]ListAppTokensRow, error) {
	rows, err := q.db.Query(ctx, listAppTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAppTokensRow{}
	for rows.Next() {
		var i ListAppTokensRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAppToken = `-- name: RevokeAppToken :one
UPDATE app_tokens
SET revoked_at = now()
WHERE id = $1
  AND revoked_at IS NULL
RETURNING id
`

// Withdraw one phone. Returning the id says whether there was a live token to
// withdraw, so pressing Remove twice is a 404 rather than a second revocation
// that moves the timestamp.
func (q *Queries) RevokeAppToken(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, revokeAppToken, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const touchAppToken = `-- name: TouchAppToken :exec
UPDATE app_tokens
SET last_used_at = now()
WHERE id = $1
`

// Record that this token was used. Written at most once a minute per token by
// the middleware, because the alternative is one UPDATE per request.
func (q *Queries) TouchAppToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAppToken, id)
	return err
}
