// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: artists.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const artistImage = `-- name: ArtistImage :one
SELECT image, content_type, source
FROM artist_images
WHERE artist_id = $1
`

type ArtistImageRow struct {
	Image       []byte `json:"image"`
	ContentType string `json:"content_type"`
	Source      string `json:"source"`
}

// The cached picture of an artist. Display and never evidence.
func (q *Queries) ArtistImage(ctx context.Context, artistID uuid.UUID) (ArtistImageRow, error) {
	row := q.db.QueryRow(ctx, artistImage, artistID)
	var i ArtistImageRow
	err := row.Scan(&i.Image, &i.ContentType, &i.Source)
	return i, err
}

const artistListTotals = `-- name: ArtistListTotals :one
WITH completeness AS (
    -- Dismissed tracks, fully dismissed releases and unmonitored releases
    -- leave the denominators, exactly as in ListArtists above; see the
    -- comments there.
    SELECT
        albums.artist_id,
        count(*) FILTER (
            WHERE measured.monitored
              AND (album_tracks.track_count = 0 OR measured.countable_count > 0)
        )::bigint AS release_count,
        count(*) FILTER (
            WHERE measured.monitored
              AND measured.countable_count > 0
              AND album_tracks.owned_count = measured.countable_count
        )::bigint AS owned_release_count
    FROM albums
    JOIN artists AS monitoring ON monitoring.id = albums.artist_id
    JOIN LATERAL (
        SELECT
            count(*)::bigint AS track_count,
            count(*) FILTER (WHERE holding.held)::bigint AS owned_count,
            count(*) FILTER (
                WHERE NOT holding.held AND dismissals.id IS NOT NULL
            )::bigint AS dismissed_count
        FROM tracks
        LEFT JOIN track_mappings
            ON track_mappings.track_id = tracks.id
           AND EXISTS (
               SELECT 1 FROM library_files
               WHERE library_files.id = track_mappings.library_file_id
                 AND library_files.missing_at IS NULL
           )
        -- The library can hold a track without mapping it onto this release:
        -- the same recording proven on a file whose identity names it, or on a
        -- file mapped onto another release's track that carries it. Counting
        -- only the mapping would leave a recording that sits on a single, an EP
        -- and a compilation owned on one of the three and missing on the other
        -- two forever, and the acquisition loop already settles those wants
        -- against either proof (OwnedFileForRecording).
        JOIN LATERAL (
            SELECT (track_mappings.id IS NOT NULL OR EXISTS (
                SELECT 1
                FROM library_file_identities
                JOIN library_files
                    ON library_files.id = library_file_identities.library_file_id
                WHERE library_file_identities.musicbrainz_recording_id
                        = tracks.musicbrainz_recording_id
                  AND library_files.missing_at IS NULL
            ) OR EXISTS (
                SELECT 1
                FROM tracks AS carrying
                JOIN track_mappings AS elsewhere
                    ON elsewhere.track_id = carrying.id
                JOIN library_files ON library_files.id = elsewhere.library_file_id
                WHERE carrying.musicbrainz_recording_id
                        = tracks.musicbrainz_recording_id
                  AND library_files.missing_at IS NULL
            )) AS held
        ) AS holding ON true
        LEFT JOIN acquisition_targets AS dismissals
            ON tracks.musicbrainz_recording_id IS NOT NULL
           AND dismissals.musicbrainz_recording_id = tracks.musicbrainz_recording_id
           AND dismissals.status = 'not_wanted'
        WHERE tracks.album_id = albums.id
    ) AS album_tracks ON true
    JOIN LATERAL (
        SELECT
            CASE monitoring.monitor_level
                WHEN 'everything' THEN true
                WHEN 'main' THEN albums.album_type IN ('album', 'ep', 'single')
                    AND NOT (albums.secondary_types
                        && '{live,compilation,remix,dj-mix,mixtape/street,demo,broadcast}'::text[])
                WHEN 'albums_eps' THEN albums.album_type IN ('album', 'ep')
                    AND NOT (albums.secondary_types
                        && '{live,compilation,remix,dj-mix,mixtape/street,demo,broadcast}'::text[])
                ELSE album_tracks.owned_count > 0
            END AS monitored,
            CASE WHEN monitoring.monitor_level = 'owned'
                 THEN album_tracks.owned_count
                 ELSE album_tracks.track_count - album_tracks.dismissed_count
            END AS countable_count
    ) AS measured ON true
    GROUP BY albums.artist_id
),
in_flight AS (
    SELECT
        COALESCE(albums.artist_id, track_albums.artist_id) AS artist_id,
        count(*)::bigint AS in_flight_count
    FROM downloads
    LEFT JOIN albums ON albums.id = downloads.album_id
    LEFT JOIN tracks ON tracks.id = downloads.track_id
    LEFT JOIN albums AS track_albums ON track_albums.id = tracks.album_id
    WHERE downloads.status IN ('queued', 'searching', 'downloading', 'importing')
      AND COALESCE(albums.artist_id, track_albums.artist_id) IS NOT NULL
    GROUP BY COALESCE(albums.artist_id, track_albums.artist_id)
),
awaiting_review AS (
    SELECT
        albums.artist_id,
        count(DISTINCT held_copies.acquisition_target_id)::bigint AS review_count
    FROM acquisition_target_files AS held_copies
    JOIN acquisition_targets AS targets
        ON targets.id = held_copies.acquisition_target_id
    JOIN albums
        ON albums.id = targets.origin_album_id
        OR (targets.musicbrainz_release_group_id IS NOT NULL
            AND albums.musicbrainz_release_group_id = targets.musicbrainz_release_group_id)
    WHERE held_copies.verdict = 'held'
      -- Only wants still being pursued, the same rule the review queue reads by
      -- (AcquisitionReviewQueue). Accepting one copy leaves its siblings held, so
      -- counting held rows alone would badge an artist for a question the queue
      -- no longer asks and send somebody looking for something that is not there.
      AND targets.status NOT IN ('acquired', 'not_wanted', 'superseded')
    GROUP BY albums.artist_id
),
counted AS (
    SELECT
        artists.followed_at,
        COALESCE(artists.source, '')::text AS source,
        COALESCE(latest_refresh.status, 'pending')::text AS refresh_status,
        COALESCE(completeness.release_count, 0)::bigint AS release_count,
        COALESCE(completeness.owned_release_count, 0)::bigint AS owned_release_count,
        COALESCE(in_flight.in_flight_count, 0)::bigint AS in_flight_count,
        COALESCE(awaiting_review.review_count, 0)::bigint AS review_count
    FROM artists
    LEFT JOIN LATERAL (
        SELECT status
        FROM jobs
        WHERE kind = 'refresh_artist_metadata'
          AND payload->>'artistId' = artists.id::text
        ORDER BY created_at DESC
        LIMIT 1
    ) AS latest_refresh ON true
    LEFT JOIN completeness ON completeness.artist_id = artists.id
    LEFT JOIN in_flight ON in_flight.artist_id = artists.id
    LEFT JOIN awaiting_review ON awaiting_review.artist_id = artists.id
    WHERE (
            $1::text = ''
            -- Escaped the same way as the page it counts; see ListArtists.
            OR concat_ws(' ', artists.name, artists.sort_name)
               ILIKE '%' || regexp_replace($1::text, '([\\%_])', '\\\1', 'g') || '%'
               ESCAPE '\'
        )
      -- The genre narrows the counts too, for the reason the search does: the
      -- numbers describe the list the reader is looking at.
      AND (
            $2::text = ''
            OR $2::text = ANY(COALESCE(artists.genres, '{}'::text[]))
        )
),
scoped AS (
    SELECT followed_at, source, refresh_status, release_count, owned_release_count, in_flight_count, review_count FROM counted
    WHERE $3::text = ''
       OR ($3::text = 'followed' AND followed_at IS NOT NULL)
       OR ($3::text = 'held' AND followed_at IS NULL)
)
SELECT
    (SELECT count(*) FILTER (WHERE followed_at IS NOT NULL) FROM counted)::bigint
        AS followed_count,
    (SELECT count(*) FILTER (WHERE followed_at IS NULL) FROM counted)::bigint
        AS held_count,
    (SELECT count(*) FROM scoped)::bigint AS all_count,
    (SELECT count(*) FROM scoped
      WHERE release_count > 0 AND owned_release_count < release_count)::bigint
        AS incomplete_count,
    (SELECT count(*) FROM scoped
      WHERE release_count > 0 AND owned_release_count = release_count)::bigint
        AS complete_count,
    (SELECT count(*) FROM scoped
      WHERE source = ''
        AND (review_count > 0 OR in_flight_count > 0
             OR refresh_status = 'failed' OR release_count = 0))::bigint
        AS attention_count,
    -- What the header states above the grid: how much of the shown list is
    -- owned. Summed over the scope rather than the page, because a page is an
    -- accident of where the user stopped scrolling.
    (SELECT COALESCE(sum(release_count), 0) FROM scoped)::bigint AS release_total,
    (SELECT COALESCE(sum(owned_release_count), 0) FROM scoped)::bigint
        AS owned_release_total,
    (
        SELECT count(*)
        FROM jobs
        WHERE kind = 'refresh_artist_metadata'
          AND status IN ('queued', 'running')
    )::bigint AS refreshing_count
`

type ArtistListTotalsParams struct {
	Query string `json:"query"`
	Genre string `json:"genre"`
	Scope string `json:"scope"`
}

type ArtistListTotalsRow struct {
	FollowedCount     int64 `json:"followed_count"`
	HeldCount         int64 `json:"held_count"`
	AllCount          int64 `json:"all_count"`
	IncompleteCount   int64 `json:"incomplete_count"`
	CompleteCount     int64 `json:"complete_count"`
	AttentionCount    int64 `json:"attention_count"`
	ReleaseTotal      int64 `json:"release_total"`
	OwnedReleaseTotal int64 `json:"owned_release_total"`
	RefreshingCount   int64 `json:"refreshing_count"`
}

// What a page of artists is a page of. Counted apart from the page itself: a
// window function would lose the total exactly when the page is empty, which is
// when the number matters most.
//
// Both halves are counted whichever scope is showing, because the page has
// always said how many artists are followed and how many are held, and a scope
// that hid one of those numbers would make the collection look smaller than it
// is. The search does apply: the counts describe the list the user is looking
// at, not the catalogue in general.
//
// The four completeness counts are the same, and for the same reason: they label
// the choices between which the user is picking, so a count that changed when a
// choice was made would be describing the answer instead of the question. They
// do honour scope, because scope is the wider question these narrow.
//
// The refresh count is deliberately not scoped or searched. It answers "is
// anything still being fetched?", which the page uses to decide whether to keep
// polling, and an artist refreshing on some other page is still refreshing.
//
// The completeness and attention CTEs are the ones in ListArtists, repeated
// rather than shared: a count that disagreed with the list it labels would be
// worse than the duplication. Change one and change the other.
func (q *Queries) ArtistListTotals(ctx context.Context, arg ArtistListTotalsParams) (ArtistListTotalsRow, error) {
	row := q.db.QueryRow(ctx, artistListTotals, arg.Query, arg.Genre, arg.Scope)
	var i ArtistListTotalsRow
	err := row.Scan(
		&i.FollowedCount,
		&i.HeldCount,
		&i.AllCount,
		&i.IncompleteCount,
		&i.CompleteCount,
		&i.AttentionCount,
		&i.ReleaseTotal,
		&i.OwnedReleaseTotal,
		&i.RefreshingCount,
	)
	return i, err
}

const artistTracksForWanting = `-- name: ArtistTracksForWanting :many
SELECT
    albums.id AS album_id,
    albums.title AS album_title,
    albums.musicbrainz_release_group_id,
    artists.name AS artist_name,
    tracks.title,
    tracks.duration_ms,
    tracks.isrc,
    tracks.musicbrainz_recording_id,
    (track_mappings.id IS NOT NULL)::boolean AS owned,
    (held.library_file_id IS NOT NULL)::boolean AS held_elsewhere
FROM albums
JOIN artists ON artists.id = albums.artist_id
JOIN tracks ON tracks.album_id = albums.id
LEFT JOIN track_mappings
    ON track_mappings.track_id = tracks.id
   AND EXISTS (
       SELECT 1 FROM library_files
       WHERE library_files.id = track_mappings.library_file_id
         AND library_files.missing_at IS NULL
   )
LEFT JOIN LATERAL (
    SELECT library_files.id AS library_file_id
    FROM library_file_identities
    JOIN library_files
        ON library_files.id = library_file_identities.library_file_id
    WHERE library_file_identities.musicbrainz_recording_id
            = tracks.musicbrainz_recording_id
      AND library_files.missing_at IS NULL
    UNION ALL
    SELECT library_files.id
    FROM tracks AS carrying
    JOIN track_mappings ON track_mappings.track_id = carrying.id
    JOIN library_files ON library_files.id = track_mappings.library_file_id
    WHERE carrying.musicbrainz_recording_id = tracks.musicbrainz_recording_id
      AND library_files.missing_at IS NULL
    LIMIT 1
) held ON true
WHERE albums.artist_id = $1
  AND CASE artists.monitor_level
          WHEN 'everything' THEN true
          WHEN 'main' THEN albums.album_type IN ('album', 'ep', 'single')
              AND NOT (albums.secondary_types
                  && '{live,compilation,remix,dj-mix,mixtape/street,demo,broadcast}'::text[])
          WHEN 'albums_eps' THEN albums.album_type IN ('album', 'ep')
              AND NOT (albums.secondary_types
                  && '{live,compilation,remix,dj-mix,mixtape/street,demo,broadcast}'::text[])
          ELSE false
      END
ORDER BY albums.release_date NULLS LAST, albums.id,
         tracks.disc_number, tracks.track_number NULLS LAST, tracks.id
`

type ArtistTracksForWantingRow struct {
	AlbumID                   uuid.UUID     `json:"album_id"`
	AlbumTitle                string        `json:"album_title"`
	MusicbrainzReleaseGroupID uuid.NullUUID `json:"musicbrainz_release_group_id"`
	ArtistName                string        `json:"artist_name"`
	Title                     string        `json:"title"`
	DurationMs                pgtype.Int4   `json:"duration_ms"`
	Isrc                      pgtype.Text   `json:"isrc"`
	MusicbrainzRecordingID    uuid.NullUUID `json:"musicbrainz_recording_id"`
	Owned                     bool          `json:"owned"`
	HeldElsewhere             bool          `json:"held_elsewhere"`
}

// Every track of every release this artist has, with the release context each
// one would be wanted from. It is the discography-wide version of what
// ListAlbumTracks answers for one release, and it is one query rather than two
// per release because a discography is hundreds of them.
//
// Owned and held elsewhere are the two ways the library can already hold a
// track, and either one is a reason not to want it: a mapping onto a present
// file, or a present file proven to be that recording without being mapped onto
// this release at all. Both are read because the acquisition loop settles a want
// against either (OwnedFileForRecording), so wanting on the mapping alone makes
// wants the loop answers with "In your library." a minute later.
//
// Only monitored releases are walked: "want everything missing" follows the
// artist's monitor level, always, and at 'owned' there is nothing new to want
// at all. An unmonitored release can still be wanted by hand from its own
// page — a manual want always wins — this is only what the discography-wide
// press reaches.
// The same recording proven on a file this release never mapped onto: a
// resolved identity naming it, or a mapping onto another release's track that
// carries it. Aliasing the inner tracks table leaves the outer one's recording
// id in scope, which is what both halves compare against.
func (q *Queries) ArtistTracksForWanting(ctx context.Context, artistID uuid.UUID) ([]ArtistTracksForWantingRow, error) {
	rows, err := q.db.Query(ctx, artistTracksForWanting, artistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArtistTracksForWantingRow{}
	for rows.Next() {
		var i ArtistTracksForWantingRow
		if err := rows.Scan(
			&i.AlbumID,
			&i.AlbumTitle,
			&i.MusicbrainzReleaseGroupID,
			&i.ArtistName,
			&i.Title,
			&i.DurationMs,
			&i.Isrc,
			&i.MusicbrainzRecordingID,
			&i.Owned,
			&i.HeldElsewhere,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const artistsMissingBiography = `-- name: ArtistsMissingBiography :many
SELECT artists.id, artists.musicbrainz_id
FROM artists
WHERE artists.musicbrainz_id IS NOT NULL
  AND artists.biography_fetched_at IS NULL
ORDER BY artists.created_at
LIMIT $1
`

type ArtistsMissingBiographyRow struct {
	ID            uuid.UUID     `json:"id"`
	MusicbrainzID uuid.NullUUID `json:"musicbrainz_id"`
}

// The artists nobody has asked an encyclopaedia about yet.
//
// Only artists with a MusicBrainz identifier, because the chain starts there:
// MusicBrainz says which Wikidata entity this is, the entity says which
// Wikipedia article, and the article is where the words come from. Nobody is
// ever asked about an artist by name.
//
// biography_fetched_at is set whatever the answer was, absence included, so an
// artist asked about once is never in this list again. The oldest question
// first, then the oldest artist, so a run through the catalogue is the same
// run every time.
func (q *Queries) ArtistsMissingBiography(ctx context.Context, batch int32) ([]ArtistsMissingBiographyRow, error) {
	rows, err := q.db.Query(ctx, artistsMissingBiography, batch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArtistsMissingBiographyRow{}
	for rows.Next() {
		var i ArtistsMissingBiographyRow
		if err := rows.Scan(&i.ID, &i.MusicbrainzID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const artistsMissingImage = `-- name: ArtistsMissingImage :many
SELECT artists.id, artists.musicbrainz_id
FROM artists
LEFT JOIN artist_images ON artist_images.artist_id = artists.id
WHERE artists.musicbrainz_id IS NOT NULL
  AND (
    artist_images.artist_id IS NULL
    OR (artist_images.image IS NULL AND artist_images.fetched_at < $1)
  )
ORDER BY artist_images.fetched_at ASC NULLS FIRST, artists.created_at
LIMIT $2
`

type ArtistsMissingImageParams struct {
	ChainChanged pgtype.Timestamptz `json:"chain_changed"`
	Batch        int32              `json:"batch"`
}

type ArtistsMissingImageRow struct {
	ID            uuid.UUID     `json:"id"`
	MusicbrainzID uuid.NullUUID `json:"musicbrainz_id"`
}

// Artists there is a picture to look for. Only those MusicBrainz knows, because
// the picture is keyed on that identifier and there is nothing to ask about
// without it.
//
// That is everyone nobody has looked for a picture of yet, and everyone whose
// row says nobody had one but says it about a chain that has since changed. A
// row with no image is the answer "asked, and there is none", which answers the
// question that was asked at the time and stops answering it when the chain
// doing the asking gains a rung — an artist written off before that would
// otherwise be skipped forever and the new rung would picture nobody. The
// caller passes the day the chain last changed (coverart.chainChanged), so
// adding a rung is a date to bump rather than a migration deleting absences by
// hand, which is what adding the last one took.
//
// Those never asked about come first, so a collection's worth of old absences
// being asked again cannot hold up an artist nobody has ever looked for at all;
// among the rest the stalest goes first. A pass records what it finds either
// way, absence included, which writes a fetched_at on the near side of the date
// above — so a batch of re-asks is answered once and not seen again until the
// chain changes again.
func (q *Queries) ArtistsMissingImage(ctx context.Context, arg ArtistsMissingImageParams) ([]ArtistsMissingImageRow, error) {
	rows, err := q.db.Query(ctx, artistsMissingImage, arg.ChainChanged, arg.Batch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArtistsMissingImageRow{}
	for rows.Next() {
		var i ArtistsMissingImageRow
		if err := rows.Scan(&i.ID, &i.MusicbrainzID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const backfillGenres = `-- name: BackfillGenres :one
WITH waiting_artists AS (
    SELECT artists.id
    FROM artists
    LEFT JOIN LATERAL (
        SELECT jobs.completed_at
        FROM jobs
        WHERE jobs.kind = 'refresh_artist_metadata'
          AND jobs.payload->>'artistId' = artists.id::text
          AND jobs.status = 'failed'
        ORDER BY jobs.completed_at DESC
        LIMIT 1
    ) last_failure ON true
    WHERE artists.musicbrainz_id IS NOT NULL
      AND artists.genres IS NULL
      AND (
        last_failure.completed_at IS NULL
        OR last_failure.completed_at < now() - interval '1 day'
      )
    ORDER BY artists.created_at
    LIMIT $1
),
waiting_albums AS (
    SELECT albums.id
    FROM albums
    LEFT JOIN LATERAL (
        SELECT jobs.completed_at
        FROM jobs
        WHERE jobs.kind = 'refresh_album_metadata'
          AND jobs.payload->>'albumId' = albums.id::text
          AND jobs.status = 'failed'
        ORDER BY jobs.completed_at DESC
        LIMIT 1
    ) last_failure ON true
    WHERE albums.musicbrainz_release_group_id IS NOT NULL
      AND albums.genres IS NULL
      AND (
        last_failure.completed_at IS NULL
        OR last_failure.completed_at < now() - interval '1 day'
      )
    ORDER BY albums.created_at
    LIMIT $1
),
queued_artists AS (
    INSERT INTO jobs (kind, payload)
    SELECT 'refresh_artist_metadata', jsonb_build_object('artistId', waiting_artists.id)
    FROM waiting_artists
    WHERE NOT EXISTS (
        SELECT 1 FROM jobs
        WHERE jobs.kind = 'refresh_artist_metadata'
          AND jobs.payload->>'artistId' = waiting_artists.id::text
          AND jobs.status IN ('queued', 'running')
    )
    RETURNING 1 AS queued_one
),
queued_albums AS (
    INSERT INTO jobs (kind, payload)
    SELECT 'refresh_album_metadata', jsonb_build_object('albumId', waiting_albums.id::text)
    FROM waiting_albums
    ON CONFLICT (kind, (payload->>'albumId'))
        WHERE kind = 'refresh_album_metadata' AND status IN ('queued', 'running')
    DO NOTHING
    RETURNING 1 AS queued_one
)
SELECT
    ((SELECT count(*) FROM waiting_artists)
        + (SELECT count(*) FROM waiting_albums))::bigint AS waiting_count,
    ((SELECT count(*) FROM queued_artists)
        + (SELECT count(*) FROM queued_albums))::bigint AS queued_count
`

type BackfillGenresRow struct {
	WaitingCount int64 `json:"waiting_count"`
	QueuedCount  int64 `json:"queued_count"`
}

// Asks for the genres nobody has asked MusicBrainz about yet.
//
// It asks MusicBrainz nothing itself. It queues the ordinary refreshes, which
// are the passes that already visit the entity and read the community's votes
// off the responses they were fetching anyway. So a catalogue that predates
// genres fills at the refresh's own pace, one request a second, with no request
// that would not have been made by somebody pressing Refresh.
//
// An artist without genres is asked for by the artist refresh. An album without
// them is asked for by its own release refresh, and that is the part that used
// to be wrong: the artist refresh only writes the release groups MusicBrainz
// credits to that artist, so an album credited to somebody else — a remix, a
// collaboration filed under the other name — was never reached by it and kept
// its NULL forever. The sweep read that NULL as "the artist still needs asking",
// queued the artist again ten minutes later, and each of those refreshes queued
// a release refresh for all 185 of the artist's release groups. Two such albums
// produced 1,494 jobs an hour, indefinitely.
//
// An entity already queued, or being refreshed now, is left alone: that pass
// will genre it, and a second job would only ask MusicBrainz the same question
// twice.
//
// One whose refresh failed within the last day is left alone too, and for a
// different reason: a batch is ordered oldest-first, so an entity whose
// MusicBrainz identifier no longer resolves would otherwise be re-queued, fail,
// and be re-queued again every pass forever, filling the batch with the same
// permanent failure and starving everything behind it. A day is long enough
// that a transient failure gets retried the same day, and short enough that a
// real answer is not put off for good.
//
// A pass queues at most one batch of each kind. Reports how many were waiting
// and how many were queued, so the sweep knows whether to come back.
func (q *Queries) BackfillGenres(ctx context.Context, batch int32) (BackfillGenresRow, error) {
	row := q.db.QueryRow(ctx, backfillGenres, batch)
	var i BackfillGenresRow
	err := row.Scan(&i.WaitingCount, &i.QueuedCount)
	return i, err
}

const catalogueGenres = `-- name: CatalogueGenres :many
SELECT DISTINCT unnest(artists.genres)::text AS genre
FROM artists
WHERE artists.genres IS NOT NULL
ORDER BY genre
`

// Every genre the catalogue holds for an artist, in alphabetical order. It is
// the list the artists browser offers to filter by, so it names only genres
// that would find somebody.
func (q *Queries) CatalogueGenres(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, catalogueGenres)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var genre string
		if err := rows.Scan(&genre); err != nil {
			return nil, err
		}
		items = append(items, genre)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createArtist = `-- name: CreateArtist :one
WITH followed_artist AS (
    INSERT INTO artists (musicbrainz_id, name, sort_name, followed_at)
    VALUES ($1, $2, $3, now())
    ON CONFLICT (musicbrainz_id) DO UPDATE
    SET followed_at = now(),
        catalogue_summary = NULL,
        name = EXCLUDED.name,
        sort_name = EXCLUDED.sort_name,
        updated_at = now()
    WHERE artists.followed_at IS NULL
    RETURNING id, musicbrainz_id, name, sort_name, followed_at, last_refreshed_at
),
queued_job AS (
    INSERT INTO jobs (kind, payload)
    SELECT 'refresh_artist_metadata', jsonb_build_object('artistId', id)
    FROM followed_artist
)
SELECT id, musicbrainz_id, name, sort_name, followed_at, last_refreshed_at
FROM followed_artist
`

type CreateArtistParams struct {
	MusicbrainzID uuid.NullUUID `json:"musicbrainz_id"`
	Name          string        `json:"name"`
	SortName      string        `json:"sort_name"`
}

type CreateArtistRow struct {
	ID              uuid.UUID          `json:"id"`
	MusicbrainzID   uuid.NullUUID      `json:"musicbrainz_id"`
	Name            string             `json:"name"`
	SortName        string             `json:"sort_name"`
	FollowedAt      pgtype.Timestamptz `json:"followed_at"`
	LastRefreshedAt pgtype.Timestamptz `json:"last_refreshed_at"`
}

// Following an artist Schall is already holding is a promotion, not a
// conflict: the artist is in the catalogue because the library contains their
// music, and the user is now asking for their releases to be kept complete.
// Promoting queues the full artist refresh, because until now only the one
// release behind an owned file had been fetched.
//
// An artist who is already followed returns no row, and the caller reports the
// conflict that genuinely is one.
func (q *Queries) CreateArtist(ctx context.Context, arg CreateArtistParams) (CreateArtistRow, error) {
	row := q.db.QueryRow(ctx, createArtist, arg.MusicbrainzID, arg.Name, arg.SortName)
	var i CreateArtistRow
	err := row.Scan(
		&i.ID,
		&i.MusicbrainzID,
		&i.Name,
		&i.SortName,
		&i.FollowedAt,
		&i.LastRefreshedAt,
	)
	return i, err
}

const followArtistByID = `-- name: FollowArtistByID :one
WITH followed_artist AS (
    UPDATE artists
    SET followed_at = now(), catalogue_summary = NULL, updated_at = now()
    WHERE artists.id = $1 AND artists.followed_at IS NULL
    RETURNING artists.id, artists.musicbrainz_id, artists.name, artists.sort_name,
              artists.followed_at, artists.last_refreshed_at
),
queued_job AS (
    INSERT INTO jobs (kind, payload)
    SELECT 'refresh_artist_metadata', jsonb_build_object('artistId', followed_artist.id)
    FROM followed_artist
    WHERE followed_artist.musicbrainz_id IS NOT NULL
)
SELECT id, musicbrainz_id, name, sort_name, followed_at, last_refreshed_at
FROM followed_artist
`

type FollowArtistByIDRow struct {
	ID              uuid.UUID          `json:"id"`
	MusicbrainzID   uuid.NullUUID      `json:"musicbrainz_id"`
	Name            string             `json:"name"`
	SortName        string             `json:"sort_name"`
	FollowedAt      pgtype.Timestamptz `json:"followed_at"`
	LastRefreshedAt pgtype.Timestamptz `json:"last_refreshed_at"`
}

// Follows an artist Schall is already holding, from the artist's own page,
// where the user is looking at the music that put them in the catalogue rather
// than at a MusicBrainz search result.
func (q *Queries) FollowArtistByID(ctx context.Context, artistID uuid.UUID) (FollowArtistByIDRow, error) {
	row := q.db.QueryRow(ctx, followArtistByID, artistID)
	var i FollowArtistByIDRow
	err := row.Scan(
		&i.ID,
		&i.MusicbrainzID,
		&i.Name,
		&i.SortName,
		&i.FollowedAt,
		&i.LastRefreshedAt,
	)
	return i, err
}

const followFeedTracks = `-- name: FollowFeedTracks :many
SELECT
    albums.id AS album_id,
    albums.title AS album_title,
    albums.musicbrainz_release_group_id,
    artists.name AS artist_name,
    tracks.title,
    tracks.duration_ms,
    tracks.isrc,
    tracks.musicbrainz_recording_id
FROM albums
JOIN artists ON artists.id = albums.artist_id
JOIN tracks ON tracks.album_id = albums.id
WHERE artists.followed_at IS NOT NULL
  AND albums.release_date IS NOT NULL
  AND albums.release_date > artists.followed_at::date
  AND tracks.musicbrainz_recording_id IS NOT NULL
  AND CASE artists.monitor_level
          WHEN 'everything' THEN true
          WHEN 'main' THEN albums.album_type IN ('album', 'ep', 'single')
              AND NOT (albums.secondary_types
                  && '{live,compilation,remix,dj-mix,mixtape/street,demo,broadcast}'::text[])
          WHEN 'albums_eps' THEN albums.album_type IN ('album', 'ep')
              AND NOT (albums.secondary_types
                  && '{live,compilation,remix,dj-mix,mixtape/street,demo,broadcast}'::text[])
          ELSE false
      END
  -- Either way the library can already hold it. A mapping onto a present file —
  -- including one onto this very track, which is the same query with carrying
  -- being tracks itself — or a present file proven to be that recording and
  -- never mapped onto this release at all. Both are read because the loop
  -- settles a want against either, so wanting on the mapping alone makes wants
  -- the loop answers with "In your library." a minute later.
  AND NOT EXISTS (
      SELECT 1
      FROM tracks AS carrying
      JOIN track_mappings ON track_mappings.track_id = carrying.id
      JOIN library_files ON library_files.id = track_mappings.library_file_id
      WHERE carrying.musicbrainz_recording_id = tracks.musicbrainz_recording_id
        AND library_files.missing_at IS NULL
  )
  AND NOT EXISTS (
      SELECT 1
      FROM library_file_identities
      JOIN library_files ON library_files.id = library_file_identities.library_file_id
      WHERE library_file_identities.musicbrainz_recording_id = tracks.musicbrainz_recording_id
        AND library_files.missing_at IS NULL
  )
  -- A recording already asked for is not asked for again, and that is also what
  -- keeps a refused one refused: a not_wanted target holds its recording, so the
  -- feed finds it and passes over rather than re-opening the decision. Only a
  -- superseded row is exempt, because the survivor it points at carries the same
  -- recording and is matched here instead.
  AND NOT EXISTS (
      SELECT 1
      FROM acquisition_targets
      WHERE acquisition_targets.musicbrainz_recording_id = tracks.musicbrainz_recording_id
        AND acquisition_targets.status <> 'superseded'
  )
ORDER BY albums.release_date, albums.id,
         tracks.disc_number, tracks.track_number NULLS LAST, tracks.id
LIMIT $1
`

type FollowFeedTracksRow struct {
	AlbumID                   uuid.UUID     `json:"album_id"`
	AlbumTitle                string        `json:"album_title"`
	MusicbrainzReleaseGroupID uuid.NullUUID `json:"musicbrainz_release_group_id"`
	ArtistName                string        `json:"artist_name"`
	Title                     string        `json:"title"`
	DurationMs                pgtype.Int4   `json:"duration_ms"`
	Isrc                      pgtype.Text   `json:"isrc"`
	MusicbrainzRecordingID    uuid.NullUUID `json:"musicbrainz_recording_id"`
}

// What the follow feed wants: tracks on releases published after the follow, by
// artists the user follows, that the library does not hold and nobody has
// already asked for.
//
// Published after the follow is the whole rule. Following an artist says "keep
// them complete from here"; it is not a press of "want the discography", which
// exists separately and reaches backwards on purpose. A release with no date is
// not wanted either — an absent date is silence, and reading it as "new" would
// make following an artist drag in every undated thing MusicBrainz holds
// against them.
//
// The monitor level filters this exactly as it filters the discography press,
// and at 'owned' the feed wants nothing at all. An unmonitored release is still
// browsable and can still be wanted by hand; this is only what arrives without
// anybody pressing anything.
//
// A track with no recording is skipped rather than wanted. Creation is
// idempotent on the recording ID, so a want without one is always new and every
// pass would make another.
func (q *Queries) FollowFeedTracks(ctx context.Context, rowLimit int32) ([]FollowFeedTracksRow, error) {
	rows, err := q.db.Query(ctx, followFeedTracks, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FollowFeedTracksRow{}
	for rows.Next() {
		var i FollowFeedTracksRow
		if err := rows.Scan(
			&i.AlbumID,
			&i.AlbumTitle,
			&i.MusicbrainzReleaseGroupID,
			&i.ArtistName,
			&i.Title,
			&i.DurationMs,
			&i.Isrc,
			&i.MusicbrainzRecordingID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArtist = `-- name: GetArtist :one
SELECT
    artists.id,
    artists.musicbrainz_id,
    artists.name,
    artists.sort_name,
    artists.followed_at,
    artists.monitor_level,
    -- When the standing "want what is missing" was set, and NULL when it is
    -- off. The page shows it as a state rather than a date; the date is here
    -- because a want made under it should be traceable to when it was asked
    -- for.
    artists.want_missing_since,
    COALESCE(artists.catalogue_summary, '')::text AS catalogue_summary,
    -- See ListArtists: an artist who is an account on another service has no
    -- discography and no completeness.
    COALESCE(artists.source, '')::text AS source,
    COALESCE(artists.external_id, '')::text AS external_id,
    artists.last_refreshed_at,
    -- What MusicBrainz's community voted this artist is, most voted first. An
    -- artist nobody has asked about yet and an artist nobody voted for both
    -- come back as an empty list here: the page shows no chips either way, and
    -- the difference only matters to the sweep that does the asking.
    COALESCE(artists.genres, '{}')::text[] AS genres,
    -- The Wikipedia summary and the article it came from. Both empty until the
    -- sweep has asked, and both stay empty for an artist no encyclopaedia has
    -- heard of.
    COALESCE(artists.biography, '')::text AS biography,
    COALESCE(artists.biography_source_url, '')::text AS biography_source_url,
    count(albums.id) AS album_count,
    COALESCE(latest_refresh.status, 'pending') AS refresh_status,
    latest_refresh.error_message AS refresh_error
FROM artists
LEFT JOIN albums ON albums.artist_id = artists.id
LEFT JOIN LATERAL (
    SELECT status, error_message
    FROM jobs
    WHERE kind = 'refresh_artist_metadata'
      AND payload->>'artistId' = artists.id::text
    ORDER BY created_at DESC
    LIMIT 1
) AS latest_refresh ON true
WHERE artists.id = $1
GROUP BY artists.id, latest_refresh.status, latest_refresh.error_message
`

type GetArtistRow struct {
	ID                 uuid.UUID          `json:"id"`
	MusicbrainzID      uuid.NullUUID      `json:"musicbrainz_id"`
	Name               string             `json:"name"`
	SortName           string             `json:"sort_name"`
	FollowedAt         pgtype.Timestamptz `json:"followed_at"`
	MonitorLevel       string             `json:"monitor_level"`
	WantMissingSince   pgtype.Timestamptz `json:"want_missing_since"`
	CatalogueSummary   string             `json:"catalogue_summary"`
	Source             string             `json:"source"`
	ExternalID         string             `json:"external_id"`
	LastRefreshedAt    pgtype.Timestamptz `json:"last_refreshed_at"`
	Genres             []string           `json:"genres"`
	Biography          string             `json:"biography"`
	BiographySourceUrl string             `json:"biography_source_url"`
	AlbumCount         int64              `json:"album_count"`
	RefreshStatus      string             `json:"refresh_status"`
	RefreshError       pgtype.Text        `json:"refresh_error"`
}

func (q *Queries) GetArtist(ctx context.Context, id uuid.UUID) (GetArtistRow, error) {
	row := q.db.QueryRow(ctx, getArtist, id)
	var i GetArtistRow
	err := row.Scan(
		&i.ID,
		&i.MusicbrainzID,
		&i.Name,
		&i.SortName,
		&i.FollowedAt,
		&i.MonitorLevel,
		&i.WantMissingSince,
		&i.CatalogueSummary,
		&i.Source,
		&i.ExternalID,
		&i.LastRefreshedAt,
		&i.Genres,
		&i.Biography,
		&i.BiographySourceUrl,
		&i.AlbumCount,
		&i.RefreshStatus,
		&i.RefreshError,
	)
	return i, err
}

const listArtists = `-- name: ListArtists :many
WITH completeness AS (
    -- Two decisions shape these numbers, and both narrow the denominator
    -- rather than counting as missing. A dismissed track — not owned, and its
    -- recording carries a not_wanted want — was decided about per track; a
    -- release the artist's monitor level does not reach was decided about up
    -- front. Neither hides anything: the discography stays browsable, and the
    -- header states the basis the fraction was computed over.
    SELECT
        albums.artist_id,
        count(*) FILTER (
            WHERE measured.monitored
              AND (album_tracks.track_count = 0 OR measured.countable_count > 0)
        )::bigint AS release_count,
        count(*) FILTER (
            WHERE measured.monitored
              AND measured.countable_count > 0
              AND album_tracks.owned_count = measured.countable_count
        )::bigint AS owned_release_count,
        COALESCE(sum(measured.countable_count) FILTER (WHERE measured.monitored), 0)::bigint
            AS track_count,
        COALESCE(sum(album_tracks.owned_count) FILTER (WHERE measured.monitored), 0)::bigint
            AS owned_track_count
    FROM albums
    JOIN artists AS monitoring ON monitoring.id = albums.artist_id
    JOIN LATERAL (
        -- Owned means the library still has a file that is this track, whether
        -- it is mapped onto it or proven to be its recording elsewhere. Still
        -- has, always: a file that went missing leaves its mapping behind, and
        -- counting it would call a release complete when nothing can play it —
        -- the same rule the releases browser counts by (albumJoins in
        -- internal/db/catalogue.go).
        SELECT
            count(*)::bigint AS track_count,
            count(*) FILTER (WHERE holding.held)::bigint AS owned_count,
            count(*) FILTER (
                WHERE NOT holding.held AND dismissals.id IS NOT NULL
            )::bigint AS dismissed_count
        FROM tracks
        LEFT JOIN track_mappings
            ON track_mappings.track_id = tracks.id
           AND EXISTS (
               SELECT 1 FROM library_files
               WHERE library_files.id = track_mappings.library_file_id
                 AND library_files.missing_at IS NULL
           )
        -- The library can hold a track without mapping it onto this release:
        -- the same recording proven on a file whose identity names it, or on a
        -- file mapped onto another release's track that carries it. Counting
        -- only the mapping would leave a recording that sits on a single, an EP
        -- and a compilation owned on one of the three and missing on the other
        -- two forever, and the acquisition loop already settles those wants
        -- against either proof (OwnedFileForRecording).
        JOIN LATERAL (
            SELECT (track_mappings.id IS NOT NULL OR EXISTS (
                SELECT 1
                FROM library_file_identities
                JOIN library_files
                    ON library_files.id = library_file_identities.library_file_id
                WHERE library_file_identities.musicbrainz_recording_id
                        = tracks.musicbrainz_recording_id
                  AND library_files.missing_at IS NULL
            ) OR EXISTS (
                SELECT 1
                FROM tracks AS carrying
                JOIN track_mappings AS elsewhere
                    ON elsewhere.track_id = carrying.id
                JOIN library_files ON library_files.id = elsewhere.library_file_id
                WHERE carrying.musicbrainz_recording_id
                        = tracks.musicbrainz_recording_id
                  AND library_files.missing_at IS NULL
            )) AS held
        ) AS holding ON true
        -- At most one target exists per recording outside 'superseded'
        -- (acquisition_targets_recording_idx), so this join cannot fan out.
        LEFT JOIN acquisition_targets AS dismissals
            ON tracks.musicbrainz_recording_id IS NOT NULL
           AND dismissals.musicbrainz_recording_id = tracks.musicbrainz_recording_id
           AND dismissals.status = 'not_wanted'
        WHERE tracks.album_id = albums.id
    ) AS album_tracks ON true
    JOIN LATERAL (
        -- What the artist's monitor level says this release is. MusicBrainz's
        -- own types decide "main": albums, EPs and singles that are not one of
        -- the secondary shapes nobody means when they ask for a discography.
        -- "owned" counts only what the library already holds — every release it
        -- reaches is complete by construction, and nothing else exists to be
        -- missing.
        SELECT
            CASE monitoring.monitor_level
                WHEN 'everything' THEN true
                WHEN 'main' THEN albums.album_type IN ('album', 'ep', 'single')
                    AND NOT (albums.secondary_types
                        && '{live,compilation,remix,dj-mix,mixtape/street,demo,broadcast}'::text[])
                WHEN 'albums_eps' THEN albums.album_type IN ('album', 'ep')
                    AND NOT (albums.secondary_types
                        && '{live,compilation,remix,dj-mix,mixtape/street,demo,broadcast}'::text[])
                ELSE album_tracks.owned_count > 0
            END AS monitored,
            CASE WHEN monitoring.monitor_level = 'owned'
                 THEN album_tracks.owned_count
                 ELSE album_tracks.track_count - album_tracks.dismissed_count
            END AS countable_count
    ) AS measured ON true
    GROUP BY albums.artist_id
),
in_flight AS (
    -- Transfers actually moving, not requests on record. A download request
    -- stays 'requested' after its files arrive, so it says what was asked for
    -- rather than what is happening now, and a card reading "downloading"
    -- forever would be worse than one that never said it.
    SELECT
        COALESCE(albums.artist_id, track_albums.artist_id) AS artist_id,
        count(*)::bigint AS in_flight_count
    FROM downloads
    LEFT JOIN albums ON albums.id = downloads.album_id
    LEFT JOIN tracks ON tracks.id = downloads.track_id
    LEFT JOIN albums AS track_albums ON track_albums.id = tracks.album_id
    WHERE downloads.status IN ('queued', 'searching', 'downloading', 'importing')
      AND COALESCE(albums.artist_id, track_albums.artist_id) IS NOT NULL
    GROUP BY COALESCE(albums.artist_id, track_albums.artist_id)
),
awaiting_review AS (
    -- A want whose copy nobody could identify is held for a person to listen to.
    -- Reaching the artist from it goes through the release the want was resolved
    -- against, either the album it came from or the release group it named. The
    -- join can match both, so targets are counted once per artist and not once
    -- per way of getting there.
    SELECT
        albums.artist_id,
        count(DISTINCT held_copies.acquisition_target_id)::bigint AS review_count
    FROM acquisition_target_files AS held_copies
    JOIN acquisition_targets AS targets
        ON targets.id = held_copies.acquisition_target_id
    JOIN albums
        ON albums.id = targets.origin_album_id
        OR (targets.musicbrainz_release_group_id IS NOT NULL
            AND albums.musicbrainz_release_group_id = targets.musicbrainz_release_group_id)
    WHERE held_copies.verdict = 'held'
      -- Only wants still being pursued, the same rule the review queue reads by
      -- (AcquisitionReviewQueue). Accepting one copy leaves its siblings held, so
      -- counting held rows alone would badge an artist for a question the queue
      -- no longer asks and send somebody looking for something that is not there.
      AND targets.status NOT IN ('acquired', 'not_wanted', 'superseded')
    GROUP BY albums.artist_id
),
listed AS (
    SELECT
        artists.id,
        artists.musicbrainz_id,
        artists.name,
        artists.sort_name,
        artists.followed_at,
        COALESCE(artists.catalogue_summary, '')::text AS catalogue_summary,
        -- Which service the artist is an account on, where they are one. An
        -- uploader on SoundCloud is in the library because a track of theirs is,
        -- and MusicBrainz has never heard of them: there is no discography to
        -- compare the library against and nothing to refresh, so completeness is
        -- not a question that can be asked about them.
        COALESCE(artists.source, '')::text AS source,
        artists.last_refreshed_at,
        COALESCE(latest_refresh.status, 'pending')::text AS refresh_status,
        latest_refresh.error_message AS refresh_error,
        COALESCE(completeness.release_count, 0)::bigint AS release_count,
        COALESCE(completeness.owned_release_count, 0)::bigint AS owned_release_count,
        COALESCE(completeness.track_count, 0)::bigint AS track_count,
        COALESCE(completeness.owned_track_count, 0)::bigint AS owned_track_count,
        COALESCE(in_flight.in_flight_count, 0)::bigint AS in_flight_count,
        COALESCE(awaiting_review.review_count, 0)::bigint AS review_count
    FROM artists
    LEFT JOIN LATERAL (
        SELECT status, error_message
        FROM jobs
        WHERE kind = 'refresh_artist_metadata'
          AND payload->>'artistId' = artists.id::text
        ORDER BY created_at DESC
        LIMIT 1
    ) AS latest_refresh ON true
    LEFT JOIN completeness ON completeness.artist_id = artists.id
    LEFT JOIN in_flight ON in_flight.artist_id = artists.id
    LEFT JOIN awaiting_review ON awaiting_review.artist_id = artists.id
    WHERE (
            $5::text = ''
            OR ($5::text = 'followed' AND artists.followed_at IS NOT NULL)
            OR ($5::text = 'held' AND artists.followed_at IS NULL)
        )
      AND (
            $6::text = ''
            -- A search box is not a pattern language, so % and _ have to be
            -- escaped to match themselves, and so does the escape character or it
            -- would eat the escapes put in beside it. One regexp pass over all
            -- three is what keeps that last part from depending on the order.
            OR concat_ws(' ', artists.name, artists.sort_name)
               ILIKE '%' || regexp_replace($6::text, '([\\%_])', '\\\1', 'g') || '%'
               ESCAPE '\'
        )
      -- A genre is picked from the list of genres the catalogue holds, so it is
      -- compared whole rather than searched for. Nothing here is a pattern, so
      -- nothing here needs escaping.
      AND (
            $7::text = ''
            OR $7::text = ANY(COALESCE(artists.genres, '{}'::text[]))
        )
)
SELECT
    listed.id, listed.musicbrainz_id, listed.name, listed.sort_name, listed.followed_at, listed.catalogue_summary, listed.source, listed.last_refreshed_at, listed.refresh_status, listed.refresh_error, listed.release_count, listed.owned_release_count, listed.track_count, listed.owned_track_count, listed.in_flight_count, listed.review_count,
    -- An artist wanting attention is one the page can point at something for:
    -- copies waiting for an ear, a transfer under way, a refresh that failed, or
    -- a discography never fetched. The last one belongs here because an artist
    -- nothing has been fetched for cannot be called complete or incomplete — the
    -- catalogue has nothing to compare the library against.
    --
    -- An artist who is an account on another service is outside all of it. The
    -- last rule above would badge every one of them, because they have no
    -- releases and never will; there is nothing to point them at.
    (
        listed.source = ''
        AND (
            listed.review_count > 0
            OR listed.in_flight_count > 0
            OR listed.refresh_status = 'failed'
            OR listed.release_count = 0
        )
    )::boolean AS needs_attention
FROM listed
WHERE $1::text = ''
   OR ($1::text = 'incomplete'
       AND listed.release_count > 0
       AND listed.owned_release_count < listed.release_count)
   OR ($1::text = 'complete'
       AND listed.release_count > 0
       AND listed.owned_release_count = listed.release_count)
   OR ($1::text = 'attention'
       AND listed.source = ''
       AND (listed.review_count > 0
            OR listed.in_flight_count > 0
            OR listed.refresh_status = 'failed'
            OR listed.release_count = 0))
ORDER BY
    CASE WHEN $2::text = 'least-complete'
         THEN listed.owned_release_count::numeric / nullif(listed.release_count, 0)
    END ASC NULLS FIRST,
    CASE WHEN $2::text = 'least-complete'
         THEN listed.owned_track_count::numeric / nullif(listed.track_count, 0)
    END ASC NULLS FIRST,
    CASE WHEN $2::text = 'most-missing'
         THEN listed.release_count - listed.owned_release_count
    END DESC NULLS LAST,
    CASE WHEN $2::text = 'most-missing'
         THEN listed.track_count - listed.owned_track_count
    END DESC NULLS LAST,
    lower(listed.sort_name), (listed.followed_at IS NULL), listed.id
LIMIT NULLIF($4::int, 0) OFFSET $3
`

type ListArtistsParams struct {
	Completeness string `json:"completeness"`
	Sort         string `json:"sort"`
	Offset       int32  `json:"offset"`
	Limit        int32  `json:"limit"`
	Scope        string `json:"scope"`
	Query        string `json:"query"`
	Genre        string `json:"genre"`
}

type ListArtistsRow struct {
	ID                uuid.UUID          `json:"id"`
	MusicbrainzID     uuid.NullUUID      `json:"musicbrainz_id"`
	Name              string             `json:"name"`
	SortName          string             `json:"sort_name"`
	FollowedAt        pgtype.Timestamptz `json:"followed_at"`
	CatalogueSummary  string             `json:"catalogue_summary"`
	Source            string             `json:"source"`
	LastRefreshedAt   pgtype.Timestamptz `json:"last_refreshed_at"`
	RefreshStatus     string             `json:"refresh_status"`
	RefreshError      pgtype.Text        `json:"refresh_error"`
	ReleaseCount      int64              `json:"release_count"`
	OwnedReleaseCount int64              `json:"owned_release_count"`
	TrackCount        int64              `json:"track_count"`
	OwnedTrackCount   int64              `json:"owned_track_count"`
	InFlightCount     int64              `json:"in_flight_count"`
	ReviewCount       int64              `json:"review_count"`
	NeedsAttention    bool               `json:"needs_attention"`
}

// An explicit limit pages the list for callers that need it. A zero limit
// returns every row for the artists landing page. Only one half of the list
// grows on purpose. Following an
// artist is a deliberate act and that set stays about as large as the user's
// attention; holding one is a side effect of owning their music, and a
// collection acquired album by album holds a long tail of artists with a single
// release each. Scope narrows the page to one of those two claims, and an empty
// scope means everyone, because every artist listed is either followed or held
// and neither is noise the user never asked for.
//
// Completeness is aggregated over the whole catalogue rather than over the page,
// because the page can be ordered and narrowed by it, and a number computed
// after the page was chosen could do neither. One grouped pass over every
// artist's tracks is what that costs, which is affordable at the size a
// self-hosted library reaches. If it ever stops being, the answer is a
// maintained column, not a cheaper approximation of how much is owned.
// Each sort is its own key, so the one that is not asked for is a column of
// NULLs and decides nothing. An artist with no releases has no completion to
// sort by and comes first under "least complete", which is where somebody
// looking for the least complete artists would want to be told that nothing is
// known about this one at all.
//
// Releases decide the order and tracks break the tie. Releases first because
// that is the fraction the card states, and a list ordered by a number it does
// not show is a list nobody can check. Tracks second because release
// completeness is nearly all-or-nothing — an artist missing one track of one
// album and an artist missing everything both own no complete release — and
// without the second key those two would sort by name, which is no answer to
// "who is least complete".
//
// Followed artists first was meant to be the last tiebreaker rather than the
// rule, and under the name sort it was the rule: every CASE above is NULL for
// every row then, so `followed_at IS NULL` led the sort. The page drew the
// seventeen followed artists in alphabetical order, then started at A again
// with the thirty-two the library merely holds, while the control said "Name".
// The reader has a scope picker for "only the ones I follow"; the sort is now
// the sort, and being followed breaks a tie.
//
// The name is folded before it is compared. This database sorts by byte, so
// every capital came before every small letter: AZALEA before American
// Football, COMPUTER DATA before Childish Gambino, and nthng after Yung Lean at
// the very end of the list. That is not an order anybody reads a list in.
//
// Sorting is still on sort_name, which is MusicBrainz's filing name — Porter
// Robinson under R, Kendrick Lamar under L, the convention a record shop uses.
// That is deliberate and it is the one thing here the reader cannot see from
// the tile.
//
// No index answers `lower(sort_name)`; artists_list_order_idx (00020) is on
// ((followed_at IS NULL), sort_name, id) and no longer matches. At this
// collection's size the sort is nothing, but a matching expression index is a
// migration, and migrations are proposed rather than written.
func (q *Queries) ListArtists(ctx context.Context, arg ListArtistsParams) ([]ListArtistsRow, error) {
	rows, err := q.db.Query(ctx, listArtists,
		arg.Completeness,
		arg.Sort,
		arg.Offset,
		arg.Limit,
		arg.Scope,
		arg.Query,
		arg.Genre,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArtistsRow{}
	for rows.Next() {
		var i ListArtistsRow
		if err := rows.Scan(
			&i.ID,
			&i.MusicbrainzID,
			&i.Name,
			&i.SortName,
			&i.FollowedAt,
			&i.CatalogueSummary,
			&i.Source,
			&i.LastRefreshedAt,
			&i.RefreshStatus,
			&i.RefreshError,
			&i.ReleaseCount,
			&i.OwnedReleaseCount,
			&i.TrackCount,
			&i.OwnedTrackCount,
			&i.InFlightCount,
			&i.ReviewCount,
			&i.NeedsAttention,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queueArtistRefresh = `-- name: QueueArtistRefresh :one
WITH existing_artist AS (
    SELECT artists.id
    FROM artists
    WHERE artists.id = $1
),
active_job AS (
    SELECT jobs.id, jobs.status, jobs.created_at
    FROM jobs
    JOIN existing_artist ON jobs.payload->>'artistId' = existing_artist.id::text
    WHERE jobs.kind = 'refresh_artist_metadata'
      AND jobs.status IN ('queued', 'running')
    ORDER BY jobs.created_at DESC
    LIMIT 1
),
created_job AS (
    INSERT INTO jobs (kind, payload)
    SELECT 'refresh_artist_metadata', jsonb_build_object('artistId', id)
    FROM existing_artist
    WHERE NOT EXISTS (SELECT 1 FROM active_job)
    RETURNING id, status, created_at
)
SELECT id, status, created_at FROM active_job
UNION ALL
SELECT id, status, created_at FROM created_job
LIMIT 1
`

type QueueArtistRefreshRow struct {
	ID        uuid.UUID          `json:"id"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) QueueArtistRefresh(ctx context.Context, artistID uuid.UUID) (QueueArtistRefreshRow, error) {
	row := q.db.QueryRow(ctx, queueArtistRefresh, artistID)
	var i QueueArtistRefreshRow
	err := row.Scan(&i.ID, &i.Status, &i.CreatedAt)
	return i, err
}

const saveArtistBiography = `-- name: SaveArtistBiography :exec
UPDATE artists
SET biography = nullif($1::text, ''),
    biography_source_url = nullif($2::text, ''),
    biography_fetched_at = now(),
    updated_at = now()
WHERE id = $3
`

type SaveArtistBiographyParams struct {
	Biography string    `json:"biography"`
	SourceUrl string    `json:"source_url"`
	ArtistID  uuid.UUID `json:"artist_id"`
}

// Records what the encyclopaedia said about one artist, including that it had
// never heard of them: an empty biography with a time beside it is the answer
// "asked, and there is no article", which is what stops the sweep asking again.
// An outage calls nothing here at all.
func (q *Queries) SaveArtistBiography(ctx context.Context, arg SaveArtistBiographyParams) error {
	_, err := q.db.Exec(ctx, saveArtistBiography, arg.Biography, arg.SourceUrl, arg.ArtistID)
	return err
}

const saveArtistImage = `-- name: SaveArtistImage :exec
INSERT INTO artist_images (artist_id, image, content_type, source, fetched_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (artist_id) DO UPDATE
SET image = EXCLUDED.image,
    content_type = EXCLUDED.content_type,
    source = EXCLUDED.source,
    fetched_at = EXCLUDED.fetched_at
`

type SaveArtistImageParams struct {
	ArtistID    uuid.UUID `json:"artist_id"`
	Image       []byte    `json:"image"`
	ContentType string    `json:"content_type"`
	Source      string    `json:"source"`
}

func (q *Queries) SaveArtistImage(ctx context.Context, arg SaveArtistImageParams) error {
	_, err := q.db.Exec(ctx, saveArtistImage,
		arg.ArtistID,
		arg.Image,
		arg.ContentType,
		arg.Source,
	)
	return err
}

const setArtistMonitorLevel = `-- name: SetArtistMonitorLevel :one
UPDATE artists
SET monitor_level = $1, updated_at = now()
WHERE id = $2
RETURNING id, monitor_level
`

type SetArtistMonitorLevelParams struct {
	MonitorLevel string    `json:"monitor_level"`
	ArtistID     uuid.UUID `json:"artist_id"`
}

type SetArtistMonitorLevelRow struct {
	ID           uuid.UUID `json:"id"`
	MonitorLevel string    `json:"monitor_level"`
}

// The monitor level decides what counts as missing and what "want everything"
// wants — never what is shown or fetched. Changing it deletes nothing:
// existing wants stay (they were asked for), owned music stays counted, and
// per-track not-wanted decisions stay permanent underneath it.
func (q *Queries) SetArtistMonitorLevel(ctx context.Context, arg SetArtistMonitorLevelParams) (SetArtistMonitorLevelRow, error) {
	row := q.db.QueryRow(ctx, setArtistMonitorLevel, arg.MonitorLevel, arg.ArtistID)
	var i SetArtistMonitorLevelRow
	err := row.Scan(&i.ID, &i.MonitorLevel)
	return i, err
}

const setArtistWantMissing = `-- name: SetArtistWantMissing :one
UPDATE artists
SET want_missing_since = CASE
        WHEN $1::boolean THEN COALESCE(want_missing_since, now())
        ELSE NULL
    END,
    updated_at = now()
WHERE id = $2
RETURNING id, want_missing_since
`

type SetArtistWantMissingParams struct {
	Wanted   bool      `json:"wanted"`
	ArtistID uuid.UUID `json:"artist_id"`
}

type SetArtistWantMissingRow struct {
	ID               uuid.UUID          `json:"id"`
	WantMissingSince pgtype.Timestamptz `json:"want_missing_since"`
}

// The standing "want what is missing" on an artist. Set, every missing track of
// every monitored release is wanted, now and as tracklists arrive; the artist
// refresh saves the release groups and queues one release refresh each, and
// those land one at a time behind MusicBrainz's rate limit, so a single press
// reaches only the releases whose tracks have already arrived.
//
// Setting it twice keeps the first time, because the standing want has not
// stopped and started; it is the same one. Clearing it stops future wanting and
// touches no want that exists, for the reason changing the monitor level does
// not: those were asked for.
func (q *Queries) SetArtistWantMissing(ctx context.Context, arg SetArtistWantMissingParams) (SetArtistWantMissingRow, error) {
	row := q.db.QueryRow(ctx, setArtistWantMissing, arg.Wanted, arg.ArtistID)
	var i SetArtistWantMissingRow
	err := row.Scan(&i.ID, &i.WantMissingSince)
	return i, err
}

const staleFollowedArtists = `-- name: StaleFollowedArtists :many
SELECT artists.id
FROM artists
WHERE artists.followed_at IS NOT NULL
  AND artists.musicbrainz_id IS NOT NULL
  AND (artists.last_refreshed_at IS NULL OR artists.last_refreshed_at < $1)
ORDER BY artists.last_refreshed_at NULLS FIRST, artists.id
LIMIT $2
`

type StaleFollowedArtistsParams struct {
	RefreshedBefore pgtype.Timestamptz `json:"refreshed_before"`
	RowLimit        int32              `json:"row_limit"`
}

// Followed artists whose catalogue nobody has looked at lately, oldest first.
// This is what the follow feed's clock asks for: a release published after the
// follow only reaches the catalogue if somebody asks MusicBrainz again, and the
// whole point of following is that nobody has to.
//
// Only artists MusicBrainz knows, because the refresh is keyed on that
// identifier and there is nothing to ask about without it. A catalogue-only
// artist is skipped entirely: holding an artist is a statement of fact about
// the library, not a request to keep them complete.
func (q *Queries) StaleFollowedArtists(ctx context.Context, arg StaleFollowedArtistsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, staleFollowedArtists, arg.RefreshedBefore, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const standingWantTracks = `-- name: StandingWantTracks :many
SELECT
    albums.id AS album_id,
    albums.title AS album_title,
    albums.musicbrainz_release_group_id,
    artists.name AS artist_name,
    tracks.title,
    tracks.duration_ms,
    tracks.isrc,
    tracks.musicbrainz_recording_id,
    (track_mappings.id IS NOT NULL)::boolean AS owned,
    (held.library_file_id IS NOT NULL)::boolean AS held_elsewhere
FROM albums
JOIN artists ON artists.id = albums.artist_id
JOIN tracks ON tracks.album_id = albums.id
LEFT JOIN track_mappings
    ON track_mappings.track_id = tracks.id
   AND EXISTS (
       SELECT 1 FROM library_files
       WHERE library_files.id = track_mappings.library_file_id
         AND library_files.missing_at IS NULL
   )
LEFT JOIN LATERAL (
    SELECT library_files.id AS library_file_id
    FROM library_file_identities
    JOIN library_files
        ON library_files.id = library_file_identities.library_file_id
    WHERE library_file_identities.musicbrainz_recording_id
            = tracks.musicbrainz_recording_id
      AND library_files.missing_at IS NULL
    UNION ALL
    SELECT library_files.id
    FROM tracks AS carrying
    JOIN track_mappings ON track_mappings.track_id = carrying.id
    JOIN library_files ON library_files.id = track_mappings.library_file_id
    WHERE carrying.musicbrainz_recording_id = tracks.musicbrainz_recording_id
      AND library_files.missing_at IS NULL
    LIMIT 1
) held ON true
WHERE albums.id = $1
  AND artists.want_missing_since IS NOT NULL
  AND CASE artists.monitor_level
          WHEN 'everything' THEN true
          WHEN 'main' THEN albums.album_type IN ('album', 'ep', 'single')
              AND NOT (albums.secondary_types
                  && '{live,compilation,remix,dj-mix,mixtape/street,demo,broadcast}'::text[])
          WHEN 'albums_eps' THEN albums.album_type IN ('album', 'ep')
              AND NOT (albums.secondary_types
                  && '{live,compilation,remix,dj-mix,mixtape/street,demo,broadcast}'::text[])
          ELSE false
      END
ORDER BY tracks.disc_number, tracks.track_number NULLS LAST, tracks.id
`

type StandingWantTracksRow struct {
	AlbumID                   uuid.UUID     `json:"album_id"`
	AlbumTitle                string        `json:"album_title"`
	MusicbrainzReleaseGroupID uuid.NullUUID `json:"musicbrainz_release_group_id"`
	ArtistName                string        `json:"artist_name"`
	Title                     string        `json:"title"`
	DurationMs                pgtype.Int4   `json:"duration_ms"`
	Isrc                      pgtype.Text   `json:"isrc"`
	MusicbrainzRecordingID    uuid.NullUUID `json:"musicbrainz_recording_id"`
	Owned                     bool          `json:"owned"`
	HeldElsewhere             bool          `json:"held_elsewhere"`
}

// Every track of one release that a standing want reaches, with the release
// context each would be wanted from. It is ArtistTracksForWanting narrowed to
// the release whose tracklist has just arrived, and it answers with no rows at
// all unless the artist has a standing want and their monitor level counts this
// release — so the caller has one thing to walk and no rule of its own to
// apply.
//
// The monitor level is read by the CASE ArtistTracksForWanting reads it by,
// which is what makes the two halves of the standing want agree: the press on
// the artist's page and the tracklist arriving an hour later want the same
// releases. At 'owned' both want nothing, because there is nothing there that
// is not already held.
// The same recording proven on a file this release never mapped onto; see
// ArtistTracksForWanting, which reads it the same way and for the same reason.
func (q *Queries) StandingWantTracks(ctx context.Context, id uuid.UUID) ([]StandingWantTracksRow, error) {
	rows, err := q.db.Query(ctx, standingWantTracks, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StandingWantTracksRow{}
	for rows.Next() {
		var i StandingWantTracksRow
		if err := rows.Scan(
			&i.AlbumID,
			&i.AlbumTitle,
			&i.MusicbrainzReleaseGroupID,
			&i.ArtistName,
			&i.Title,
			&i.DurationMs,
			&i.Isrc,
			&i.MusicbrainzRecordingID,
			&i.Owned,
			&i.HeldElsewhere,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unfollowArtist = `-- name: UnfollowArtist :one
WITH target AS (
    SELECT artists.id, artists.musicbrainz_id, artists.name, artists.sort_name
    FROM artists
    WHERE artists.id = $1 AND artists.followed_at IS NOT NULL
),
reach AS (
    SELECT
        (
            SELECT count(*)
            FROM track_mappings
            JOIN tracks ON tracks.id = track_mappings.track_id
            JOIN albums ON albums.id = tracks.album_id
            WHERE albums.artist_id = target.id
        )::bigint AS mapped_track_count,
        EXISTS (
            SELECT 1
            FROM library_file_identities
            JOIN tracks
              ON tracks.musicbrainz_recording_id
               = library_file_identities.musicbrainz_recording_id
            JOIN albums ON albums.id = tracks.album_id
            WHERE albums.artist_id = target.id
              AND library_file_identities.kind = 'external'
        ) AS has_identified_file,
        EXISTS (
            SELECT 1
            FROM download_requests
            JOIN albums ON albums.id = download_requests.album_id
            WHERE albums.artist_id = target.id
              AND download_requests.status = 'requested'
        ) AS has_open_download
    FROM target
),
decision AS (
    -- One sentence saying why an artist nobody follows is still listed. The
    -- reasons are ordered by how directly the user can see them: owned tracks
    -- first, then a file that is resolved but not yet matched, then music that
    -- has not arrived yet.
    SELECT
        (
            reach.mapped_track_count > 0
            OR reach.has_identified_file
            OR reach.has_open_download
        ) AS held,
        CASE
            WHEN reach.mapped_track_count = 1 THEN format(
                'Unfollowed on %s. Kept because your library holds 1 of their tracks.',
                to_char(now(), 'FMDD Mon YYYY'))
            WHEN reach.mapped_track_count > 1 THEN format(
                'Unfollowed on %s. Kept because your library holds %s of their tracks.',
                to_char(now(), 'FMDD Mon YYYY'), reach.mapped_track_count)
            WHEN reach.has_identified_file THEN format(
                'Unfollowed on %s. Kept because a file in your library is identified as their music.',
                to_char(now(), 'FMDD Mon YYYY'))
            WHEN reach.has_open_download THEN format(
                'Unfollowed on %s. Kept while a download of their music is still in progress.',
                to_char(now(), 'FMDD Mon YYYY'))
            ELSE ''
        END AS catalogue_summary
    FROM reach
),
cancelled_artist_jobs AS (
    UPDATE jobs
    SET status = 'cancelled', completed_at = now(), updated_at = now()
    WHERE kind = 'refresh_artist_metadata'
      AND status = 'queued'
      AND payload->>'artistId' = (SELECT target.id::text FROM target)
),
cancelled_album_jobs AS (
    UPDATE jobs
    SET status = 'cancelled', completed_at = now(), updated_at = now()
    WHERE kind = 'refresh_album_metadata'
      AND status = 'queued'
      AND NOT (SELECT held FROM decision)
      AND payload->>'albumId' IN (
          SELECT albums.id::text FROM albums
          WHERE albums.artist_id = (SELECT target.id FROM target)
      )
),
held_artist AS (
    UPDATE artists
    SET followed_at = NULL,
        catalogue_summary = (SELECT catalogue_summary FROM decision),
        updated_at = now()
    WHERE id = (SELECT target.id FROM target) AND (SELECT held FROM decision)
    RETURNING id
),
released_artist AS (
    DELETE FROM artists
    WHERE id = (SELECT target.id FROM target) AND NOT (SELECT held FROM decision)
    RETURNING id
)
SELECT
    target.id,
    target.musicbrainz_id,
    target.name,
    target.sort_name,
    decision.held,
    decision.catalogue_summary,
    reach.mapped_track_count
FROM target, decision, reach
`

type UnfollowArtistRow struct {
	ID               uuid.UUID     `json:"id"`
	MusicbrainzID    uuid.NullUUID `json:"musicbrainz_id"`
	Name             string        `json:"name"`
	SortName         string        `json:"sort_name"`
	Held             pgtype.Bool   `json:"held"`
	CatalogueSummary string        `json:"catalogue_summary"`
	MappedTrackCount int64         `json:"mapped_track_count"`
}

// Unfollowing is demotion, not deletion.
//
// Following says "keep this artist's releases complete". Unfollowing withdraws
// exactly that intent, and nothing else. It must not withdraw the separate fact
// that the library contains their music, because `albums` and `tracks` cascade
// from `artists`: deleting a followed artist would take the mappings for owned
// files with it, and a user who unfollowed an artist to stop tracking releases
// would silently lose the record of the music they already have.
//
// So the question unfollowing asks is not "did you want this artist?" but "does
// the library still reach them?". Three things count as reach, and each of them
// is something the cascade would destroy:
//
//   - a track mapping, present or missing. A missing file is a disconnected
//     drive, not a decision, and a manual mapping is permanent by rule.
//   - a proven external identity naming one of their recordings. The file is
//     resolved and waiting for matching to run; the catalogue is what is late,
//     not the evidence.
//   - an open download request for one of their albums. `download_requests`
//     cascades too, so releasing the artist mid-acquisition would take the
//     request, its transfers, and its import history with it. Asking for the
//     music is a statement that it is wanted, and once it lands the owned files
//     make the hold genuine on their own.
//
// Reached, the artist is demoted to held and keeps everything: every release,
// including the ones the library does not reach. Pruning those would discard
// manually selected editions, which are permanent by the same rule as manual
// mappings, and it would buy nothing — missing counts are already scoped to
// followed artists, so a release nobody follows reports nothing as missing.
// Keeping them also makes re-following free of a MusicBrainz refetch.
//
// Unreached, there is nothing to keep and no honest sentence to write about why
// the artist is still listed, so the row is deleted. That delete is safe
// precisely because the reach checks found nothing for the cascade to take.
// A demoted artist is no longer tracked for completeness, so the refresh that
// would fetch their full discography is no longer wanted. A released artist is
// about to stop existing. Neither should leave work queued behind them; a
// refresh already running is left alone rather than interrupted mid-flight.
// Album refreshes are cancelled only for a released artist, whose albums are
// about to be cascaded away, leaving the job with nothing to refresh. A demoted
// artist keeps their releases, so work already queued against them still has a
// subject and still produces the tracks an owned file may need.
func (q *Queries) UnfollowArtist(ctx context.Context, artistID uuid.UUID) (UnfollowArtistRow, error) {
	row := q.db.QueryRow(ctx, unfollowArtist, artistID)
	var i UnfollowArtistRow
	err := row.Scan(
		&i.ID,
		&i.MusicbrainzID,
		&i.Name,
		&i.SortName,
		&i.Held,
		&i.CatalogueSummary,
		&i.MappedTrackCount,
	)
	return i, err
}
