// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package db

import (
	"context"
)

const dashboardSummary = `-- name: DashboardSummary :one
SELECT
    (SELECT count(*) FROM artists WHERE followed_at IS NOT NULL)::bigint AS artist_count,
    (SELECT count(*) FROM artists WHERE followed_at IS NULL)::bigint AS catalogue_artist_count,
    (SELECT count(*) FROM albums)::bigint AS album_count,
    (SELECT count(*) FROM tracks)::bigint AS track_count,
    -- The badge and the Wishlist tab count the same set: wants whose status is
    -- unresolved, pending, or searching. These are the wants the list calls
    -- open, so the number names exactly what the linked tab shows.
    (SELECT count(*) FROM acquisition_targets
        WHERE status IN ('unresolved', 'pending', 'searching'))::bigint
        AS open_want_count,
    -- What the Downloads page calls open, counted the way that page counts it:
    -- one per request that has not finished, never one per file inside it. The
    -- badge and the list have to agree or the badge is not about anything the
    -- reader can go and look at — it used to add the individual transfers to the
    -- requests, so a single album being fetched read as a dozen things happening.
    -- The same rule is written once more as downloadViewOpen in
    -- internal/db/downloads.go, which is the filter the badge links to. Change
    -- one and change the other, or the badge counts what the screen will not show.
    (SELECT count(*) FROM download_requests
        WHERE status IN ('requested', 'started'))::bigint
        AS active_download_count,
    -- Running and waiting are counted apart because they are not the same news.
    -- A catalogue refresh queues one job per album, so a healthy installation
    -- routinely has hundreds waiting behind three workers — and the overview
    -- used to add them together and call the total "jobs running", which read
    -- as six hundred things happening at once.
    (SELECT count(*) FROM jobs WHERE status = 'running')::bigint
        AS running_job_count,
    (SELECT count(*) FROM jobs WHERE status = 'queued')::bigint
        AS queued_job_count
`

type DashboardSummaryRow struct {
	ArtistCount          int64 `json:"artist_count"`
	CatalogueArtistCount int64 `json:"catalogue_artist_count"`
	AlbumCount           int64 `json:"album_count"`
	TrackCount           int64 `json:"track_count"`
	OpenWantCount        int64 `json:"open_want_count"`
	ActiveDownloadCount  int64 `json:"active_download_count"`
	RunningJobCount      int64 `json:"running_job_count"`
	QueuedJobCount       int64 `json:"queued_job_count"`
}

func (q *Queries) DashboardSummary(ctx context.Context) (DashboardSummaryRow, error) {
	row := q.db.QueryRow(ctx, dashboardSummary)
	var i DashboardSummaryRow
	err := row.Scan(
		&i.ArtistCount,
		&i.CatalogueArtistCount,
		&i.AlbumCount,
		&i.TrackCount,
		&i.OpenWantCount,
		&i.ActiveDownloadCount,
		&i.RunningJobCount,
		&i.QueuedJobCount,
	)
	return i, err
}
