// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: labels.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const advanceLabelRefresh = `-- name: AdvanceLabelRefresh :exec
UPDATE labels
SET releases_offset = $1, updated_at = now()
WHERE id = $2
`

type AdvanceLabelRefreshParams struct {
	ReleasesOffset int32     `json:"releases_offset"`
	LabelID        uuid.UUID `json:"label_id"`
}

// Where the next pass starts. Written after every page, so a walk stopped by a
// restart or a rate limit resumes at the page it reached.
func (q *Queries) AdvanceLabelRefresh(ctx context.Context, arg AdvanceLabelRefreshParams) error {
	_, err := q.db.Exec(ctx, advanceLabelRefresh, arg.ReleasesOffset, arg.LabelID)
	return err
}

const completeLabelRefresh = `-- name: CompleteLabelRefresh :exec
UPDATE labels
SET releases_offset = 0, last_refreshed_at = now(), updated_at = now()
WHERE id = $1
`

// The walk reached the end of the label's releases. The position goes back to
// the start, because the next walk is a fresh look for what has been published
// since, and the refresh date is what the feed reads to decide when that is.
func (q *Queries) CompleteLabelRefresh(ctx context.Context, labelID uuid.UUID) error {
	_, err := q.db.Exec(ctx, completeLabelRefresh, labelID)
	return err
}

const createLabel = `-- name: CreateLabel :one

WITH followed_label AS (
    INSERT INTO labels (musicbrainz_id, name, label_type, country, disambiguation, followed_at)
    VALUES (
        $1, $2, $3,
        $4, $5, now()
    )
    ON CONFLICT (musicbrainz_id) DO UPDATE
    SET followed_at = now(),
        name = EXCLUDED.name,
        label_type = EXCLUDED.label_type,
        country = EXCLUDED.country,
        disambiguation = EXCLUDED.disambiguation,
        -- A new follow walks the catalogue from the start again, so a label
        -- that was unfollowed halfway through a walk does not resume into the
        -- middle of one.
        releases_offset = 0,
        updated_at = now()
    WHERE labels.followed_at IS NULL
    RETURNING id, musicbrainz_id, name, label_type, country, disambiguation,
              monitor_level, followed_at, last_refreshed_at
),
queued_job AS (
    INSERT INTO jobs (kind, payload)
    SELECT 'refresh_label_metadata', jsonb_build_object('labelId', id)
    FROM followed_label
)
SELECT id, musicbrainz_id, name, label_type, country, disambiguation,
       monitor_level, followed_at, last_refreshed_at
FROM followed_label
`

type CreateLabelParams struct {
	MusicbrainzID  uuid.UUID `json:"musicbrainz_id"`
	Name           string    `json:"name"`
	LabelType      string    `json:"label_type"`
	Country        string    `json:"country"`
	Disambiguation string    `json:"disambiguation"`
}

type CreateLabelRow struct {
	ID              uuid.UUID          `json:"id"`
	MusicbrainzID   uuid.UUID          `json:"musicbrainz_id"`
	Name            string             `json:"name"`
	LabelType       string             `json:"label_type"`
	Country         string             `json:"country"`
	Disambiguation  string             `json:"disambiguation"`
	MonitorLevel    string             `json:"monitor_level"`
	FollowedAt      pgtype.Timestamptz `json:"followed_at"`
	LastRefreshedAt pgtype.Timestamptz `json:"last_refreshed_at"`
}

// A label is a company that publishes music, held by its MusicBrainz
// identifier. Following one says "keep what this label publishes complete", the
// same statement following an artist makes, and the follow feed acts on both.
// Follows a label chosen from a MusicBrainz search.
//
// A label Schall already has a row for is promoted rather than rejected: the
// row survives an unfollow, so following again is the same decision made a
// second time. A label that is already followed returns no row, and the caller
// reports the conflict that genuinely is one.
//
// The follow queues the walk over the label's releases, because until now
// nothing about this label had been fetched.
func (q *Queries) CreateLabel(ctx context.Context, arg CreateLabelParams) (CreateLabelRow, error) {
	row := q.db.QueryRow(ctx, createLabel,
		arg.MusicbrainzID,
		arg.Name,
		arg.LabelType,
		arg.Country,
		arg.Disambiguation,
	)
	var i CreateLabelRow
	err := row.Scan(
		&i.ID,
		&i.MusicbrainzID,
		&i.Name,
		&i.LabelType,
		&i.Country,
		&i.Disambiguation,
		&i.MonitorLevel,
		&i.FollowedAt,
		&i.LastRefreshedAt,
	)
	return i, err
}

const followFeedLabelTracks = `-- name: FollowFeedLabelTracks :many
SELECT
    labels.id AS label_id,
    labels.name AS label_name,
    albums.id AS album_id,
    albums.title AS album_title,
    albums.musicbrainz_release_group_id,
    artists.name AS artist_name,
    tracks.title,
    tracks.duration_ms,
    tracks.isrc,
    tracks.musicbrainz_recording_id
FROM label_releases
JOIN labels ON labels.id = label_releases.label_id
JOIN albums ON albums.id = label_releases.album_id
JOIN artists ON artists.id = albums.artist_id
JOIN tracks ON tracks.album_id = albums.id
JOIN LATERAL (
    -- What the library holds of this release. Owned means a present file is
    -- that track's — mapped onto it, or proven to be its recording on a file
    -- mapped nowhere or mapped onto another release that carries it. The same
    -- two proofs the acquisition loop settles a want against, so a release the
    -- loop would call complete is counted complete here.
    SELECT
        count(*)::bigint AS track_count,
        count(*) FILTER (WHERE holding.held)::bigint AS owned_count
    FROM tracks
    JOIN LATERAL (
        SELECT (EXISTS (
            SELECT 1
            FROM track_mappings
            JOIN library_files ON library_files.id = track_mappings.library_file_id
            WHERE track_mappings.track_id = tracks.id
              AND library_files.missing_at IS NULL
        ) OR EXISTS (
            SELECT 1
            FROM library_file_identities
            JOIN library_files
                ON library_files.id = library_file_identities.library_file_id
            WHERE library_file_identities.musicbrainz_recording_id
                    = tracks.musicbrainz_recording_id
              AND library_files.missing_at IS NULL
        ) OR EXISTS (
            SELECT 1
            FROM tracks AS carrying
            JOIN track_mappings AS elsewhere ON elsewhere.track_id = carrying.id
            JOIN library_files ON library_files.id = elsewhere.library_file_id
            WHERE carrying.musicbrainz_recording_id = tracks.musicbrainz_recording_id
              AND library_files.missing_at IS NULL
        )) AS held
    ) AS holding ON true
    WHERE tracks.album_id = albums.id
) AS album_tracks ON true
JOIN LATERAL (
    -- What the label's monitor level says this release is, decided by
    -- MusicBrainz's own types exactly as an artist's level decides it.
    SELECT
        CASE labels.monitor_level
            WHEN 'everything' THEN true
            WHEN 'main' THEN albums.album_type IN ('album', 'ep', 'single')
                AND NOT (albums.secondary_types
                    && '{live,compilation,remix,dj-mix,mixtape/street,demo,broadcast}'::text[])
            WHEN 'albums_eps' THEN albums.album_type IN ('album', 'ep')
                AND NOT (albums.secondary_types
                    && '{live,compilation,remix,dj-mix,mixtape/street,demo,broadcast}'::text[])
            ELSE album_tracks.owned_count > 0
        END AS monitored
) AS measured ON true
WHERE labels.followed_at IS NOT NULL
  AND albums.release_date IS NOT NULL
  AND albums.release_date > labels.followed_at::date
  AND tracks.musicbrainz_recording_id IS NOT NULL
  AND measured.monitored
  AND NOT EXISTS (
      SELECT 1
      FROM tracks AS carrying
      JOIN track_mappings ON track_mappings.track_id = carrying.id
      JOIN library_files ON library_files.id = track_mappings.library_file_id
      WHERE carrying.musicbrainz_recording_id = tracks.musicbrainz_recording_id
        AND library_files.missing_at IS NULL
  )
  AND NOT EXISTS (
      SELECT 1
      FROM library_file_identities
      JOIN library_files ON library_files.id = library_file_identities.library_file_id
      WHERE library_file_identities.musicbrainz_recording_id = tracks.musicbrainz_recording_id
        AND library_files.missing_at IS NULL
  )
  AND NOT EXISTS (
      SELECT 1
      FROM acquisition_targets
      WHERE acquisition_targets.musicbrainz_recording_id = tracks.musicbrainz_recording_id
        AND acquisition_targets.status <> 'superseded'
  )
ORDER BY albums.release_date, albums.id,
         tracks.disc_number, tracks.track_number NULLS LAST, tracks.id
LIMIT $1
`

type FollowFeedLabelTracksRow struct {
	LabelID                   uuid.UUID     `json:"label_id"`
	LabelName                 string        `json:"label_name"`
	AlbumID                   uuid.UUID     `json:"album_id"`
	AlbumTitle                string        `json:"album_title"`
	MusicbrainzReleaseGroupID uuid.NullUUID `json:"musicbrainz_release_group_id"`
	ArtistName                string        `json:"artist_name"`
	Title                     string        `json:"title"`
	DurationMs                pgtype.Int4   `json:"duration_ms"`
	Isrc                      pgtype.Text   `json:"isrc"`
	MusicbrainzRecordingID    uuid.NullUUID `json:"musicbrainz_recording_id"`
}

// The tracks the feed reaches through a followed label: music published by that
// label after it was followed, that the library does not hold and nobody has
// asked for. It is FollowFeedTracks asked through `label_releases` instead of
// through the release's artist, and every exclusion in it is the same one, for
// the same reason — the loop settles a want against either kind of proof, and a
// recording already decided about stays decided.
func (q *Queries) FollowFeedLabelTracks(ctx context.Context, rowLimit int32) ([]FollowFeedLabelTracksRow, error) {
	rows, err := q.db.Query(ctx, followFeedLabelTracks, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FollowFeedLabelTracksRow{}
	for rows.Next() {
		var i FollowFeedLabelTracksRow
		if err := rows.Scan(
			&i.LabelID,
			&i.LabelName,
			&i.AlbumID,
			&i.AlbumTitle,
			&i.MusicbrainzReleaseGroupID,
			&i.ArtistName,
			&i.Title,
			&i.DurationMs,
			&i.Isrc,
			&i.MusicbrainzRecordingID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLabel = `-- name: GetLabel :one
SELECT
    labels.id,
    labels.musicbrainz_id,
    labels.name,
    labels.label_type,
    labels.country,
    labels.disambiguation,
    labels.monitor_level,
    labels.followed_at,
    labels.last_refreshed_at,
    COALESCE(latest_refresh.status, 'pending')::text AS refresh_status,
    latest_refresh.error_message AS refresh_error
FROM labels
LEFT JOIN LATERAL (
    SELECT status, error_message
    FROM jobs
    WHERE kind = 'refresh_label_metadata'
      AND payload->>'labelId' = labels.id::text
    ORDER BY created_at DESC
    LIMIT 1
) AS latest_refresh ON true
WHERE labels.id = $1
`

type GetLabelRow struct {
	ID              uuid.UUID          `json:"id"`
	MusicbrainzID   uuid.UUID          `json:"musicbrainz_id"`
	Name            string             `json:"name"`
	LabelType       string             `json:"label_type"`
	Country         string             `json:"country"`
	Disambiguation  string             `json:"disambiguation"`
	MonitorLevel    string             `json:"monitor_level"`
	FollowedAt      pgtype.Timestamptz `json:"followed_at"`
	LastRefreshedAt pgtype.Timestamptz `json:"last_refreshed_at"`
	RefreshStatus   string             `json:"refresh_status"`
	RefreshError    pgtype.Text        `json:"refresh_error"`
}

func (q *Queries) GetLabel(ctx context.Context, id uuid.UUID) (GetLabelRow, error) {
	row := q.db.QueryRow(ctx, getLabel, id)
	var i GetLabelRow
	err := row.Scan(
		&i.ID,
		&i.MusicbrainzID,
		&i.Name,
		&i.LabelType,
		&i.Country,
		&i.Disambiguation,
		&i.MonitorLevel,
		&i.FollowedAt,
		&i.LastRefreshedAt,
		&i.RefreshStatus,
		&i.RefreshError,
	)
	return i, err
}

const labelForRefresh = `-- name: LabelForRefresh :one

SELECT id, musicbrainz_id, name, releases_offset, followed_at
FROM labels
WHERE id = $1
`

type LabelForRefreshRow struct {
	ID             uuid.UUID          `json:"id"`
	MusicbrainzID  uuid.UUID          `json:"musicbrainz_id"`
	Name           string             `json:"name"`
	ReleasesOffset int32              `json:"releases_offset"`
	FollowedAt     pgtype.Timestamptz `json:"followed_at"`
}

// QueueLabelRefresh is handwritten in internal/db/labels.go: the unique
// index on active refresh_label_metadata jobs (00070_labels.sql) means two
// concurrent asks can both attempt the insert, and one of them has to catch
// the resulting 23505 rather than rely on a read-then-insert that cannot see
// the other transaction's uncommitted row.
// What one pass over a label's releases needs: which label MusicBrainz is being
// asked about, where the last pass stopped, and whether it is still followed.
// An unfollow can land between one pass queuing the next and that pass
// running, and the refresher reads followed_at to stop there rather than
// keep walking a label nobody asked about any more.
func (q *Queries) LabelForRefresh(ctx context.Context, labelID uuid.UUID) (LabelForRefreshRow, error) {
	row := q.db.QueryRow(ctx, labelForRefresh, labelID)
	var i LabelForRefreshRow
	err := row.Scan(
		&i.ID,
		&i.MusicbrainzID,
		&i.Name,
		&i.ReleasesOffset,
		&i.FollowedAt,
	)
	return i, err
}

const labelReleases = `-- name: LabelReleases :many
SELECT
    albums.id,
    albums.title,
    albums.musicbrainz_release_group_id,
    albums.release_date,
    albums.album_type,
    albums.secondary_types,
    artists.id AS artist_id,
    artists.name AS artist_name,
    album_tracks.track_count,
    album_tracks.owned_count AS owned_track_count,
    measured.monitored::boolean AS monitored
FROM label_releases
JOIN labels ON labels.id = label_releases.label_id
JOIN albums ON albums.id = label_releases.album_id
JOIN artists ON artists.id = albums.artist_id
JOIN LATERAL (
    -- What the library holds of this release. Owned means a present file is
    -- that track's — mapped onto it, or proven to be its recording on a file
    -- mapped nowhere or mapped onto another release that carries it. The same
    -- two proofs the acquisition loop settles a want against, so a release the
    -- loop would call complete is counted complete here.
    SELECT
        count(*)::bigint AS track_count,
        count(*) FILTER (WHERE holding.held)::bigint AS owned_count
    FROM tracks
    JOIN LATERAL (
        SELECT (EXISTS (
            SELECT 1
            FROM track_mappings
            JOIN library_files ON library_files.id = track_mappings.library_file_id
            WHERE track_mappings.track_id = tracks.id
              AND library_files.missing_at IS NULL
        ) OR EXISTS (
            SELECT 1
            FROM library_file_identities
            JOIN library_files
                ON library_files.id = library_file_identities.library_file_id
            WHERE library_file_identities.musicbrainz_recording_id
                    = tracks.musicbrainz_recording_id
              AND library_files.missing_at IS NULL
        ) OR EXISTS (
            SELECT 1
            FROM tracks AS carrying
            JOIN track_mappings AS elsewhere ON elsewhere.track_id = carrying.id
            JOIN library_files ON library_files.id = elsewhere.library_file_id
            WHERE carrying.musicbrainz_recording_id = tracks.musicbrainz_recording_id
              AND library_files.missing_at IS NULL
        )) AS held
    ) AS holding ON true
    WHERE tracks.album_id = albums.id
) AS album_tracks ON true
JOIN LATERAL (
    -- What the label's monitor level says this release is, decided by
    -- MusicBrainz's own types exactly as an artist's level decides it.
    SELECT
        CASE labels.monitor_level
            WHEN 'everything' THEN true
            WHEN 'main' THEN albums.album_type IN ('album', 'ep', 'single')
                AND NOT (albums.secondary_types
                    && '{live,compilation,remix,dj-mix,mixtape/street,demo,broadcast}'::text[])
            WHEN 'albums_eps' THEN albums.album_type IN ('album', 'ep')
                AND NOT (albums.secondary_types
                    && '{live,compilation,remix,dj-mix,mixtape/street,demo,broadcast}'::text[])
            ELSE album_tracks.owned_count > 0
        END AS monitored
) AS measured ON true
WHERE label_releases.label_id = $1
ORDER BY albums.release_date DESC NULLS LAST, lower(albums.title), albums.id
`

type LabelReleasesRow struct {
	ID                        uuid.UUID     `json:"id"`
	Title                     string        `json:"title"`
	MusicbrainzReleaseGroupID uuid.NullUUID `json:"musicbrainz_release_group_id"`
	ReleaseDate               pgtype.Date   `json:"release_date"`
	AlbumType                 string        `json:"album_type"`
	SecondaryTypes            []string      `json:"secondary_types"`
	ArtistID                  uuid.UUID     `json:"artist_id"`
	ArtistName                string        `json:"artist_name"`
	TrackCount                int64         `json:"track_count"`
	OwnedTrackCount           int64         `json:"owned_track_count"`
	Monitored                 bool          `json:"monitored"`
}

// What one label published, newest first, with how much of each the library
// holds. Every release is listed, whatever the monitor level says: the level
// decides what counts as missing, never what is shown.
func (q *Queries) LabelReleases(ctx context.Context, labelID uuid.UUID) ([]LabelReleasesRow, error) {
	rows, err := q.db.Query(ctx, labelReleases, labelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LabelReleasesRow{}
	for rows.Next() {
		var i LabelReleasesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.MusicbrainzReleaseGroupID,
			&i.ReleaseDate,
			&i.AlbumType,
			&i.SecondaryTypes,
			&i.ArtistID,
			&i.ArtistName,
			&i.TrackCount,
			&i.OwnedTrackCount,
			&i.Monitored,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkLabelRelease = `-- name: LinkLabelRelease :exec
INSERT INTO label_releases (label_id, album_id)
VALUES ($1, $2)
ON CONFLICT (label_id, album_id) DO NOTHING
`

type LinkLabelReleaseParams struct {
	LabelID uuid.UUID `json:"label_id"`
	AlbumID uuid.UUID `json:"album_id"`
}

// Records that a label published a release. The release group is already in the
// catalogue by the time this is called; this is only the fact that links them,
// and saying it twice says the same thing.
func (q *Queries) LinkLabelRelease(ctx context.Context, arg LinkLabelReleaseParams) error {
	_, err := q.db.Exec(ctx, linkLabelRelease, arg.LabelID, arg.AlbumID)
	return err
}

const listLabels = `-- name: ListLabels :many
SELECT
    labels.id,
    labels.musicbrainz_id,
    labels.name,
    labels.label_type,
    labels.country,
    labels.disambiguation,
    labels.monitor_level,
    labels.followed_at,
    labels.last_refreshed_at,
    COALESCE(counted.release_count, 0)::bigint AS release_count,
    COALESCE(counted.owned_release_count, 0)::bigint AS owned_release_count,
    COALESCE(counted.track_count, 0)::bigint AS track_count,
    COALESCE(counted.owned_track_count, 0)::bigint AS owned_track_count,
    COALESCE(latest_refresh.status, 'pending')::text AS refresh_status
FROM labels
LEFT JOIN LATERAL (
    SELECT
        count(*)::bigint AS release_count,
        count(*) FILTER (
            WHERE album_tracks.track_count > 0
              AND album_tracks.owned_count = album_tracks.track_count
        )::bigint AS owned_release_count,
        COALESCE(sum(album_tracks.track_count), 0)::bigint AS track_count,
        COALESCE(sum(album_tracks.owned_count), 0)::bigint AS owned_track_count
    FROM label_releases
    JOIN albums ON albums.id = label_releases.album_id
    JOIN LATERAL (
    -- What the library holds of this release. Owned means a present file is
    -- that track's — mapped onto it, or proven to be its recording on a file
    -- mapped nowhere or mapped onto another release that carries it. The same
    -- two proofs the acquisition loop settles a want against, so a release the
    -- loop would call complete is counted complete here.
    SELECT
        count(*)::bigint AS track_count,
        count(*) FILTER (WHERE holding.held)::bigint AS owned_count
    FROM tracks
    JOIN LATERAL (
        SELECT (EXISTS (
            SELECT 1
            FROM track_mappings
            JOIN library_files ON library_files.id = track_mappings.library_file_id
            WHERE track_mappings.track_id = tracks.id
              AND library_files.missing_at IS NULL
        ) OR EXISTS (
            SELECT 1
            FROM library_file_identities
            JOIN library_files
                ON library_files.id = library_file_identities.library_file_id
            WHERE library_file_identities.musicbrainz_recording_id
                    = tracks.musicbrainz_recording_id
              AND library_files.missing_at IS NULL
        ) OR EXISTS (
            SELECT 1
            FROM tracks AS carrying
            JOIN track_mappings AS elsewhere ON elsewhere.track_id = carrying.id
            JOIN library_files ON library_files.id = elsewhere.library_file_id
            WHERE carrying.musicbrainz_recording_id = tracks.musicbrainz_recording_id
              AND library_files.missing_at IS NULL
        )) AS held
    ) AS holding ON true
    WHERE tracks.album_id = albums.id
) AS album_tracks ON true
JOIN LATERAL (
    -- What the label's monitor level says this release is, decided by
    -- MusicBrainz's own types exactly as an artist's level decides it.
    SELECT
        CASE labels.monitor_level
            WHEN 'everything' THEN true
            WHEN 'main' THEN albums.album_type IN ('album', 'ep', 'single')
                AND NOT (albums.secondary_types
                    && '{live,compilation,remix,dj-mix,mixtape/street,demo,broadcast}'::text[])
            WHEN 'albums_eps' THEN albums.album_type IN ('album', 'ep')
                AND NOT (albums.secondary_types
                    && '{live,compilation,remix,dj-mix,mixtape/street,demo,broadcast}'::text[])
            ELSE album_tracks.owned_count > 0
        END AS monitored
) AS measured ON true
    WHERE label_releases.label_id = labels.id
      AND measured.monitored
) AS counted ON true
LEFT JOIN LATERAL (
    SELECT status
    FROM jobs
    WHERE kind = 'refresh_label_metadata'
      AND payload->>'labelId' = labels.id::text
    ORDER BY created_at DESC
    LIMIT 1
) AS latest_refresh ON true
ORDER BY labels.followed_at IS NULL, lower(labels.name), labels.id
`

type ListLabelsRow struct {
	ID                uuid.UUID          `json:"id"`
	MusicbrainzID     uuid.UUID          `json:"musicbrainz_id"`
	Name              string             `json:"name"`
	LabelType         string             `json:"label_type"`
	Country           string             `json:"country"`
	Disambiguation    string             `json:"disambiguation"`
	MonitorLevel      string             `json:"monitor_level"`
	FollowedAt        pgtype.Timestamptz `json:"followed_at"`
	LastRefreshedAt   pgtype.Timestamptz `json:"last_refreshed_at"`
	ReleaseCount      int64              `json:"release_count"`
	OwnedReleaseCount int64              `json:"owned_release_count"`
	TrackCount        int64              `json:"track_count"`
	OwnedTrackCount   int64              `json:"owned_track_count"`
	RefreshStatus     string             `json:"refresh_status"`
}

// Every label Schall holds, with how much of what it published the library has.
//
// The list is not paged. Both halves of it are labels somebody chose: a
// followed label was followed by hand, and a held one is a followed label that
// was let go and kept its releases. Neither half grows on its own the way the
// artists list does, where owning one album adds an artist.
func (q *Queries) ListLabels(ctx context.Context) ([]ListLabelsRow, error) {
	rows, err := q.db.Query(ctx, listLabels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLabelsRow{}
	for rows.Next() {
		var i ListLabelsRow
		if err := rows.Scan(
			&i.ID,
			&i.MusicbrainzID,
			&i.Name,
			&i.LabelType,
			&i.Country,
			&i.Disambiguation,
			&i.MonitorLevel,
			&i.FollowedAt,
			&i.LastRefreshedAt,
			&i.ReleaseCount,
			&i.OwnedReleaseCount,
			&i.TrackCount,
			&i.OwnedTrackCount,
			&i.RefreshStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setLabelMonitorLevel = `-- name: SetLabelMonitorLevel :one
UPDATE labels
SET monitor_level = $1, updated_at = now()
WHERE id = $2
RETURNING id, monitor_level
`

type SetLabelMonitorLevelParams struct {
	MonitorLevel string    `json:"monitor_level"`
	LabelID      uuid.UUID `json:"label_id"`
}

type SetLabelMonitorLevelRow struct {
	ID           uuid.UUID `json:"id"`
	MonitorLevel string    `json:"monitor_level"`
}

// What counts as one of this label's releases. It changes counting and what the
// feed wants next, and deletes nothing: wants already made were asked for.
func (q *Queries) SetLabelMonitorLevel(ctx context.Context, arg SetLabelMonitorLevelParams) (SetLabelMonitorLevelRow, error) {
	row := q.db.QueryRow(ctx, setLabelMonitorLevel, arg.MonitorLevel, arg.LabelID)
	var i SetLabelMonitorLevelRow
	err := row.Scan(&i.ID, &i.MonitorLevel)
	return i, err
}

const staleFollowedLabels = `-- name: StaleFollowedLabels :many
SELECT labels.id
FROM labels
WHERE labels.followed_at IS NOT NULL
  AND (
      labels.releases_offset > 0
      OR labels.last_refreshed_at IS NULL
      OR labels.last_refreshed_at < $1
  )
ORDER BY labels.last_refreshed_at NULLS FIRST, labels.id
LIMIT $2
`

type StaleFollowedLabelsParams struct {
	RefreshedBefore pgtype.Timestamptz `json:"refreshed_before"`
	RowLimit        int32              `json:"row_limit"`
}

// The followed labels nobody has asked MusicBrainz about lately. A label part
// way through a walk is stale whatever its refresh date says, because the walk
// has not finished and the rest of its releases have not been seen at all.
func (q *Queries) StaleFollowedLabels(ctx context.Context, arg StaleFollowedLabelsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, staleFollowedLabels, arg.RefreshedBefore, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unfollowLabel = `-- name: UnfollowLabel :one
WITH target AS (
    SELECT labels.id
    FROM labels
    WHERE labels.id = $1 AND labels.followed_at IS NOT NULL
),
cancelled_jobs AS (
    UPDATE jobs
    SET status = 'cancelled', completed_at = now(), updated_at = now()
    WHERE kind = 'refresh_label_metadata'
      AND status = 'queued'
      AND payload->>'labelId' = (SELECT target.id::text FROM target)
)
UPDATE labels
SET followed_at = NULL, releases_offset = 0, updated_at = now()
WHERE id = (SELECT target.id FROM target)
RETURNING id, musicbrainz_id, name, label_type, country, disambiguation,
          monitor_level, followed_at, last_refreshed_at
`

type UnfollowLabelRow struct {
	ID              uuid.UUID          `json:"id"`
	MusicbrainzID   uuid.UUID          `json:"musicbrainz_id"`
	Name            string             `json:"name"`
	LabelType       string             `json:"label_type"`
	Country         string             `json:"country"`
	Disambiguation  string             `json:"disambiguation"`
	MonitorLevel    string             `json:"monitor_level"`
	FollowedAt      pgtype.Timestamptz `json:"followed_at"`
	LastRefreshedAt pgtype.Timestamptz `json:"last_refreshed_at"`
}

// Unfollowing is demotion, not deletion — the same rule as for an artist, for a
// simpler reason. Nothing hangs off a label: `label_releases` says which
// releases it published, and the releases themselves belong to their artists
// and would survive the row being deleted. What deleting would throw away is
// the record of a walk over thousands of releases, so that following again
// would have to fetch every one of them a second time.
//
// Work already queued for the label is stopped. A label nobody follows is not
// one whose catalogue is worth another page of requests; a walk already running
// is left alone rather than interrupted mid-flight.
func (q *Queries) UnfollowLabel(ctx context.Context, labelID uuid.UUID) (UnfollowLabelRow, error) {
	row := q.db.QueryRow(ctx, unfollowLabel, labelID)
	var i UnfollowLabelRow
	err := row.Scan(
		&i.ID,
		&i.MusicbrainzID,
		&i.Name,
		&i.LabelType,
		&i.Country,
		&i.Disambiguation,
		&i.MonitorLevel,
		&i.FollowedAt,
		&i.LastRefreshedAt,
	)
	return i, err
}
