// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AcquisitionTarget struct {
	ID                        uuid.UUID          `json:"id"`
	Origin                    string             `json:"origin"`
	OriginAlbumID             uuid.NullUUID      `json:"origin_album_id"`
	EntryArtist               string             `json:"entry_artist"`
	EntryTitle                string             `json:"entry_title"`
	EntryAlbum                string             `json:"entry_album"`
	EntryDurationMs           pgtype.Int4        `json:"entry_duration_ms"`
	EntryIsrc                 pgtype.Text        `json:"entry_isrc"`
	MusicbrainzRecordingID    uuid.NullUUID      `json:"musicbrainz_recording_id"`
	MusicbrainzReleaseGroupID uuid.NullUUID      `json:"musicbrainz_release_group_id"`
	ResolutionMethod          pgtype.Text        `json:"resolution_method"`
	ResolvedAt                pgtype.Timestamptz `json:"resolved_at"`
	Status                    string             `json:"status"`
	ReviewReason              pgtype.Text        `json:"review_reason"`
	Summary                   string             `json:"summary"`
	LastError                 pgtype.Text        `json:"last_error"`
	Attempts                  int32              `json:"attempts"`
	LastAttemptAt             pgtype.Timestamptz `json:"last_attempt_at"`
	NextAttemptAt             pgtype.Timestamptz `json:"next_attempt_at"`
	AcquiredLibraryFileID     uuid.NullUUID      `json:"acquired_library_file_id"`
	AcquiredAt                pgtype.Timestamptz `json:"acquired_at"`
	NotWantedAt               pgtype.Timestamptz `json:"not_wanted_at"`
	SupersededByID            uuid.NullUUID      `json:"superseded_by_id"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	AnchorFingerprint         pgtype.Text        `json:"anchor_fingerprint"`
	AnchorSource              pgtype.Text        `json:"anchor_source"`
	AnchorReference           pgtype.Text        `json:"anchor_reference"`
	AnchorSeconds             pgtype.Int4        `json:"anchor_seconds"`
	AnchorFetchedAt           pgtype.Timestamptz `json:"anchor_fetched_at"`
	AnchorUnavailable         pgtype.Text        `json:"anchor_unavailable"`
	AnchorAttempts            int32              `json:"anchor_attempts"`
	AnchorNextAttemptAt       pgtype.Timestamptz `json:"anchor_next_attempt_at"`
	UpgradeOfLibraryFileID    uuid.NullUUID      `json:"upgrade_of_library_file_id"`
	AnchorLabel               pgtype.Text        `json:"anchor_label"`
	AnchorViews               pgtype.Int8        `json:"anchor_views"`
	EntryExplicit             pgtype.Bool        `json:"entry_explicit"`
	RecheckReason             pgtype.Text        `json:"recheck_reason"`
	RecheckAfter              pgtype.Timestamptz `json:"recheck_after"`
	RecheckAttempts           int32              `json:"recheck_attempts"`
	BelowFloorStreak          int16              `json:"below_floor_streak"`
	BelowFloorSince           pgtype.Timestamptz `json:"below_floor_since"`
	FloorWaivedAt             pgtype.Timestamptz `json:"floor_waived_at"`
}

type AcquisitionTargetAttempt struct {
	ID                  uuid.UUID          `json:"id"`
	AcquisitionTargetID uuid.UUID          `json:"acquisition_target_id"`
	Attempt             int32              `json:"attempt"`
	Outcome             string             `json:"outcome"`
	Detail              pgtype.Text        `json:"detail"`
	RecordedAt          pgtype.Timestamptz `json:"recorded_at"`
}

type AcquisitionTargetCandidate struct {
	AcquisitionTargetID       uuid.UUID     `json:"acquisition_target_id"`
	MusicbrainzRecordingID    uuid.UUID     `json:"musicbrainz_recording_id"`
	MusicbrainzReleaseGroupID uuid.NullUUID `json:"musicbrainz_release_group_id"`
	ArtistName                string        `json:"artist_name"`
	ReleaseTitle              pgtype.Text   `json:"release_title"`
	TrackTitle                string        `json:"track_title"`
	DurationMs                pgtype.Int4   `json:"duration_ms"`
	Isrc                      pgtype.Text   `json:"isrc"`
	Rank                      int32         `json:"rank"`
	Agrees                    []string      `json:"agrees"`
	Differs                   []string      `json:"differs"`
	Summary                   string        `json:"summary"`
}

type AcquisitionTargetFile struct {
	ID                      uuid.UUID          `json:"id"`
	AcquisitionTargetID     uuid.UUID          `json:"acquisition_target_id"`
	Provider                string             `json:"provider"`
	SourceUsername          string             `json:"source_username"`
	RemotePath              string             `json:"remote_path"`
	FileName                string             `json:"file_name"`
	SizeBytes               pgtype.Int8        `json:"size_bytes"`
	Verdict                 string             `json:"verdict"`
	DecidedBy               string             `json:"decided_by"`
	Summary                 string             `json:"summary"`
	Evidence                []byte             `json:"evidence"`
	DownloadRequestID       uuid.NullUUID      `json:"download_request_id"`
	LibraryFileID           uuid.NullUUID      `json:"library_file_id"`
	DecidedAt               pgtype.Timestamptz `json:"decided_at"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	FileRemovedAt           pgtype.Timestamptz `json:"file_removed_at"`
	AudioFingerprint        pgtype.Text        `json:"audio_fingerprint"`
	AudioFingerprintSeconds pgtype.Int4        `json:"audio_fingerprint_seconds"`
	Waveform                []byte             `json:"waveform"`
}

type AcquisitionTargetRejectedRecording struct {
	ID                        uuid.UUID          `json:"id"`
	AcquisitionTargetID       uuid.UUID          `json:"acquisition_target_id"`
	MusicbrainzRecordingID    uuid.UUID          `json:"musicbrainz_recording_id"`
	Summary                   string             `json:"summary"`
	DecidedBy                 string             `json:"decided_by"`
	DecidedAt                 pgtype.Timestamptz `json:"decided_at"`
	MusicbrainzReleaseGroupID uuid.NullUUID      `json:"musicbrainz_release_group_id"`
	ResolutionMethod          pgtype.Text        `json:"resolution_method"`
}

type Album struct {
	ID                            uuid.UUID          `json:"id"`
	ArtistID                      uuid.UUID          `json:"artist_id"`
	MusicbrainzReleaseGroupID     uuid.NullUUID      `json:"musicbrainz_release_group_id"`
	Title                         string             `json:"title"`
	ReleaseDate                   pgtype.Date        `json:"release_date"`
	AlbumType                     string             `json:"album_type"`
	CoverUrl                      pgtype.Text        `json:"cover_url"`
	CreatedAt                     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                     pgtype.Timestamptz `json:"updated_at"`
	PreferredMusicbrainzReleaseID uuid.NullUUID      `json:"preferred_musicbrainz_release_id"`
	SecondaryTypes                []string           `json:"secondary_types"`
	TrackCount                    int32              `json:"track_count"`
	OwnedTrackCount               int32              `json:"owned_track_count"`
	DismissedTrackCount           int32              `json:"dismissed_track_count"`
	Genres                        []string           `json:"genres"`
}

type AlbumArtistCredit struct {
	AlbumID             uuid.UUID          `json:"album_id"`
	Position            int32              `json:"position"`
	CreditedName        string             `json:"credited_name"`
	MusicbrainzArtistID uuid.NullUUID      `json:"musicbrainz_artist_id"`
	JoinPhrase          string             `json:"join_phrase"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type AppToken struct {
	ID         uuid.UUID          `json:"id"`
	Name       string             `json:"name"`
	TokenHash  []byte             `json:"token_hash"`
	CreatedBy  string             `json:"created_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

type Artist struct {
	ID                 uuid.UUID          `json:"id"`
	MusicbrainzID      uuid.NullUUID      `json:"musicbrainz_id"`
	Name               string             `json:"name"`
	SortName           string             `json:"sort_name"`
	FollowedAt         pgtype.Timestamptz `json:"followed_at"`
	LastRefreshedAt    pgtype.Timestamptz `json:"last_refreshed_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	CatalogueSummary   pgtype.Text        `json:"catalogue_summary"`
	MonitorLevel       string             `json:"monitor_level"`
	Source             pgtype.Text        `json:"source"`
	ExternalID         pgtype.Text        `json:"external_id"`
	Genres             []string           `json:"genres"`
	Biography          pgtype.Text        `json:"biography"`
	BiographySourceUrl pgtype.Text        `json:"biography_source_url"`
	BiographyFetchedAt pgtype.Timestamptz `json:"biography_fetched_at"`
	WantMissingSince   pgtype.Timestamptz `json:"want_missing_since"`
}

type ArtistImage struct {
	ArtistID    uuid.UUID          `json:"artist_id"`
	Image       []byte             `json:"image"`
	ContentType string             `json:"content_type"`
	Source      string             `json:"source"`
	FetchedAt   pgtype.Timestamptz `json:"fetched_at"`
}

type Download struct {
	ID                 uuid.UUID          `json:"id"`
	AlbumID            uuid.NullUUID      `json:"album_id"`
	TrackID            uuid.NullUUID      `json:"track_id"`
	Provider           string             `json:"provider"`
	ProviderDownloadID pgtype.Text        `json:"provider_download_id"`
	Status             string             `json:"status"`
	SourceUsername     pgtype.Text        `json:"source_username"`
	SourcePath         pgtype.Text        `json:"source_path"`
	ErrorMessage       pgtype.Text        `json:"error_message"`
	QueuedAt           pgtype.Timestamptz `json:"queued_at"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DownloadRequestID  uuid.NullUUID      `json:"download_request_id"`
	RemotePath         pgtype.Text        `json:"remote_path"`
	SizeBytes          int64              `json:"size_bytes"`
	TransferredBytes   int64              `json:"transferred_bytes"`
	ProviderTransferID pgtype.Text        `json:"provider_transfer_id"`
	ProviderState      pgtype.Text        `json:"provider_state"`
	LocalPath          pgtype.Text        `json:"local_path"`
	LibraryFileID      uuid.NullUUID      `json:"library_file_id"`
	Attempt            int32              `json:"attempt"`
}

type DownloadImportDecision struct {
	ID                  uuid.UUID          `json:"id"`
	DownloadRequestID   uuid.UUID          `json:"download_request_id"`
	FileName            string             `json:"file_name"`
	TrackID             uuid.UUID          `json:"track_id"`
	ObservedFingerprint string             `json:"observed_fingerprint"`
	Note                pgtype.Text        `json:"note"`
	DecidedAt           pgtype.Timestamptz `json:"decided_at"`
}

type DownloadImportReview struct {
	ID                uuid.UUID          `json:"id"`
	DownloadRequestID uuid.UUID          `json:"download_request_id"`
	Kind              string             `json:"kind"`
	Detail            pgtype.Text        `json:"detail"`
	RecordedAt        pgtype.Timestamptz `json:"recorded_at"`
	Evidence          []byte             `json:"evidence"`
}

type DownloadRequest struct {
	ID                      uuid.UUID          `json:"id"`
	AlbumID                 uuid.NullUUID      `json:"album_id"`
	Provider                string             `json:"provider"`
	SourceUsername          string             `json:"source_username"`
	SourceDirectory         string             `json:"source_directory"`
	Status                  string             `json:"status"`
	FileCount               int32              `json:"file_count"`
	ExpectedTrackCount      int32              `json:"expected_track_count"`
	TotalSizeBytes          int64              `json:"total_size_bytes"`
	Format                  string             `json:"format"`
	AverageBitRate          pgtype.Int4        `json:"average_bit_rate"`
	Score                   float64            `json:"score"`
	Reasons                 []string           `json:"reasons"`
	Files                   []byte             `json:"files"`
	RequestedAt             pgtype.Timestamptz `json:"requested_at"`
	CancelledAt             pgtype.Timestamptz `json:"cancelled_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	StartedAt               pgtype.Timestamptz `json:"started_at"`
	ErrorMessage            pgtype.Text        `json:"error_message"`
	ImportStatus            string             `json:"import_status"`
	ImportError             pgtype.Text        `json:"import_error"`
	ImportPath              pgtype.Text        `json:"import_path"`
	ImportedAt              pgtype.Timestamptz `json:"imported_at"`
	DuplicateAcknowledgedAt pgtype.Timestamptz `json:"duplicate_acknowledged_at"`
	DuplicateEvidence       []byte             `json:"duplicate_evidence"`
	AcquisitionTargetID     uuid.NullUUID      `json:"acquisition_target_id"`
}

type DownloadTransferAttempt struct {
	ID               uuid.UUID          `json:"id"`
	DownloadID       uuid.UUID          `json:"download_id"`
	Attempt          int32              `json:"attempt"`
	Outcome          string             `json:"outcome"`
	Detail           pgtype.Text        `json:"detail"`
	TransferredBytes int64              `json:"transferred_bytes"`
	RecordedAt       pgtype.Timestamptz `json:"recorded_at"`
}

type DuplicateResolutionSetting struct {
	Singleton bool               `json:"singleton"`
	Enabled   bool               `json:"enabled"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type FileCoverArt struct {
	LibraryFileID uuid.UUID          `json:"library_file_id"`
	Image         []byte             `json:"image"`
	ContentType   string             `json:"content_type"`
	Source        string             `json:"source"`
	FetchedAt     pgtype.Timestamptz `json:"fetched_at"`
}

type ImportSetting struct {
	Singleton        bool               `json:"singleton"`
	SourceRetention  string             `json:"source_retention"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	AcoustidApiKey   string             `json:"acoustid_api_key"`
	AcoustidEnabled  bool               `json:"acoustid_enabled"`
	TranscodeEnabled bool               `json:"transcode_enabled"`
	TranscodeTarget  string             `json:"transcode_target"`
	TranscodeBitrate string             `json:"transcode_bitrate"`
	TranscodeWhen    string             `json:"transcode_when"`
}

type ImportTranscode struct {
	LocalPath       string             `json:"local_path"`
	SourceFormat    string             `json:"source_format"`
	SourceSizeBytes int64              `json:"source_size_bytes"`
	TargetFormat    string             `json:"target_format"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Job struct {
	ID           uuid.UUID          `json:"id"`
	Kind         string             `json:"kind"`
	Status       string             `json:"status"`
	Payload      []byte             `json:"payload"`
	Attempts     int32              `json:"attempts"`
	MaxAttempts  int32              `json:"max_attempts"`
	RunAfter     pgtype.Timestamptz `json:"run_after"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Label struct {
	ID              uuid.UUID          `json:"id"`
	MusicbrainzID   uuid.UUID          `json:"musicbrainz_id"`
	Name            string             `json:"name"`
	LabelType       string             `json:"label_type"`
	Country         string             `json:"country"`
	Disambiguation  string             `json:"disambiguation"`
	MonitorLevel    string             `json:"monitor_level"`
	FollowedAt      pgtype.Timestamptz `json:"followed_at"`
	LastRefreshedAt pgtype.Timestamptz `json:"last_refreshed_at"`
	ReleasesOffset  int32              `json:"releases_offset"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type LabelRelease struct {
	LabelID     uuid.UUID          `json:"label_id"`
	AlbumID     uuid.UUID          `json:"album_id"`
	FirstSeenAt pgtype.Timestamptz `json:"first_seen_at"`
}

type LibraryFile struct {
	ID                     uuid.UUID          `json:"id"`
	Path                   string             `json:"path"`
	SizeBytes              int64              `json:"size_bytes"`
	ModifiedAt             pgtype.Timestamptz `json:"modified_at"`
	Fingerprint            pgtype.Text        `json:"fingerprint"`
	ArtistTag              pgtype.Text        `json:"artist_tag"`
	AlbumTag               pgtype.Text        `json:"album_tag"`
	TitleTag               pgtype.Text        `json:"title_tag"`
	DiscNumber             pgtype.Int4        `json:"disc_number"`
	TrackNumber            pgtype.Int4        `json:"track_number"`
	DurationMs             pgtype.Int4        `json:"duration_ms"`
	MusicbrainzRecordingID uuid.NullUUID      `json:"musicbrainz_recording_id"`
	Isrc                   pgtype.Text        `json:"isrc"`
	ScannedAt              pgtype.Timestamptz `json:"scanned_at"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	LibraryRootID          uuid.NullUUID      `json:"library_root_id"`
	MissingAt              pgtype.Timestamptz `json:"missing_at"`
	ScanError              pgtype.Text        `json:"scan_error"`
	MatchStatus            string             `json:"match_status"`
	MatchCandidateCount    int32              `json:"match_candidate_count"`
	ResolutionStatus       string             `json:"resolution_status"`
	ResolutionSummary      pgtype.Text        `json:"resolution_summary"`
	ResolutionAttemptedAt  pgtype.Timestamptz `json:"resolution_attempted_at"`
	ResolutionError        pgtype.Text        `json:"resolution_error"`
	DuplicateKeptAt        pgtype.Timestamptz `json:"duplicate_kept_at"`
	BitRateKbps            pgtype.Int4        `json:"bit_rate_kbps"`
	SampleRateHz           pgtype.Int4        `json:"sample_rate_hz"`
	Channels               pgtype.Int4        `json:"channels"`
	MeasuredDurationMs     pgtype.Int4        `json:"measured_duration_ms"`
	PropertiesReadAt       pgtype.Timestamptz `json:"properties_read_at"`
	ReplaygainTrackGain    pgtype.Float8      `json:"replaygain_track_gain"`
	ReplaygainTrackPeak    pgtype.Float8      `json:"replaygain_track_peak"`
	LoudnessMeasuredAt     pgtype.Timestamptz `json:"loudness_measured_at"`
	SpectralCutoffHz       pgtype.Int4        `json:"spectral_cutoff_hz"`
	AudioEncoder           pgtype.Text        `json:"audio_encoder"`
	TranscodeSuspected     pgtype.Bool        `json:"transcode_suspected"`
	SpectrumReadAt         pgtype.Timestamptz `json:"spectrum_read_at"`
	TranscodedFromFormat   pgtype.Text        `json:"transcoded_from_format"`
	OriginalSizeBytes      pgtype.Int8        `json:"original_size_bytes"`
	TranscodeCheckedAt     pgtype.Timestamptz `json:"transcode_checked_at"`
	UpgradeRefusedAt       pgtype.Timestamptz `json:"upgrade_refused_at"`
	// The upload that put this file here. Cleared after the one replacement check so a later re-identification cannot delete a file because of an old upload.
	ArrivedByUploadID         uuid.NullUUID `json:"arrived_by_upload_id"`
	WitnessFingerprint        pgtype.Text   `json:"witness_fingerprint"`
	WitnessFingerprintSeconds pgtype.Int4   `json:"witness_fingerprint_seconds"`
}

type LibraryFileCandidate struct {
	ID                        uuid.UUID          `json:"id"`
	LibraryFileID             uuid.UUID          `json:"library_file_id"`
	Provider                  string             `json:"provider"`
	MusicbrainzRecordingID    uuid.UUID          `json:"musicbrainz_recording_id"`
	MusicbrainzReleaseGroupID uuid.NullUUID      `json:"musicbrainz_release_group_id"`
	ArtistName                string             `json:"artist_name"`
	ReleaseTitle              pgtype.Text        `json:"release_title"`
	TrackTitle                string             `json:"track_title"`
	DurationMs                pgtype.Int4        `json:"duration_ms"`
	Isrc                      pgtype.Text        `json:"isrc"`
	Rank                      int32              `json:"rank"`
	Agrees                    []string           `json:"agrees"`
	Differs                   []string           `json:"differs"`
	Summary                   string             `json:"summary"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
}

type LibraryFileIdentity struct {
	ID                        uuid.UUID          `json:"id"`
	LibraryFileID             uuid.UUID          `json:"library_file_id"`
	Kind                      string             `json:"kind"`
	Provider                  string             `json:"provider"`
	MusicbrainzRecordingID    uuid.NullUUID      `json:"musicbrainz_recording_id"`
	MusicbrainzReleaseGroupID uuid.NullUUID      `json:"musicbrainz_release_group_id"`
	ArtistName                pgtype.Text        `json:"artist_name"`
	ReleaseTitle              pgtype.Text        `json:"release_title"`
	TrackTitle                pgtype.Text        `json:"track_title"`
	DurationMs                pgtype.Int4        `json:"duration_ms"`
	Isrc                      pgtype.Text        `json:"isrc"`
	Method                    string             `json:"method"`
	Confidence                pgtype.Float4      `json:"confidence"`
	IsManual                  bool               `json:"is_manual"`
	Summary                   string             `json:"summary"`
	Evidence                  []byte             `json:"evidence"`
	DecidedAt                 pgtype.Timestamptz `json:"decided_at"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	Source                    pgtype.Text        `json:"source"`
	ExternalID                pgtype.Text        `json:"external_id"`
	ExternalUrl               pgtype.Text        `json:"external_url"`
	AdmittedByFileID          uuid.NullUUID      `json:"admitted_by_file_id"`
	AdmittedByProof           pgtype.Text        `json:"admitted_by_proof"`
	RemixerName               pgtype.Text        `json:"remixer_name"`
}

type LibraryFileKeepRead struct {
	ID      uuid.UUID          `json:"id"`
	LeaseID uuid.UUID          `json:"lease_id"`
	RunID   uuid.NullUUID      `json:"run_id"`
	Signal  string             `json:"signal"`
	Outcome string             `json:"outcome"`
	Detail  string             `json:"detail"`
	ReadAt  pgtype.Timestamptz `json:"read_at"`
}

type LibraryFileLease struct {
	ID                     uuid.UUID          `json:"id"`
	LibraryFileID          uuid.NullUUID      `json:"library_file_id"`
	LibraryPath            string             `json:"library_path"`
	MusicbrainzRecordingID uuid.UUID          `json:"musicbrainz_recording_id"`
	RunID                  uuid.UUID          `json:"run_id"`
	AcquisitionTargetID    uuid.UUID          `json:"acquisition_target_id"`
	State                  string             `json:"state"`
	GrantedAt              pgtype.Timestamptz `json:"granted_at"`
	ExpiresAt              pgtype.Timestamptz `json:"expires_at"`
	Extensions             int32              `json:"extensions"`
	ExtendedReason         string             `json:"extended_reason"`
	RemovesAt              pgtype.Timestamptz `json:"removes_at"`
	LeavingRunID           uuid.NullUUID      `json:"leaving_run_id"`
	KeptBy                 pgtype.Text        `json:"kept_by"`
	ReleasedAt             pgtype.Timestamptz `json:"released_at"`
	RemovedAt              pgtype.Timestamptz `json:"removed_at"`
	SettledRunID           uuid.NullUUID      `json:"settled_run_id"`
}

type LibraryFileMove struct {
	ID            uuid.UUID          `json:"id"`
	RunID         uuid.UUID          `json:"run_id"`
	LibraryFileID uuid.UUID          `json:"library_file_id"`
	FromPath      string             `json:"from_path"`
	ToPath        string             `json:"to_path"`
	Status        string             `json:"status"`
	Error         pgtype.Text        `json:"error"`
	PlannedAt     pgtype.Timestamptz `json:"planned_at"`
	MovedAt       pgtype.Timestamptz `json:"moved_at"`
}

type LibraryFileRemoval struct {
	ID                     uuid.UUID          `json:"id"`
	LibraryFileID          uuid.UUID          `json:"library_file_id"`
	LibraryPath            string             `json:"library_path"`
	SizeBytes              int64              `json:"size_bytes"`
	MusicbrainzRecordingID uuid.UUID          `json:"musicbrainz_recording_id"`
	KeptLibraryFileID      uuid.NullUUID      `json:"kept_library_file_id"`
	KeptPath               string             `json:"kept_path"`
	RemovedBy              string             `json:"removed_by"`
	Reason                 string             `json:"reason"`
	RemovedAt              pgtype.Timestamptz `json:"removed_at"`
	UnlinkedAt             pgtype.Timestamptz `json:"unlinked_at"`
	UnlinkError            string             `json:"unlink_error"`
}

type LibraryFileSetAside struct {
	LibraryFileID uuid.UUID          `json:"library_file_id"`
	DecidedBy     string             `json:"decided_by"`
	DecidedAt     pgtype.Timestamptz `json:"decided_at"`
}

type LibraryLayoutSetting struct {
	Singleton bool               `json:"singleton"`
	Template  string             `json:"template"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type LibraryRoot struct {
	ID            uuid.UUID          `json:"id"`
	Path          string             `json:"path"`
	Enabled       bool               `json:"enabled"`
	LastScannedAt pgtype.Timestamptz `json:"last_scanned_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Listen struct {
	ListenedAt     pgtype.Timestamptz `json:"listened_at"`
	ArtistName     string             `json:"artist_name"`
	TrackName      string             `json:"track_name"`
	ReleaseName    pgtype.Text        `json:"release_name"`
	RecordingMbid  uuid.NullUUID      `json:"recording_mbid"`
	ReleaseMbid    uuid.NullUUID      `json:"release_mbid"`
	CaaReleaseMbid uuid.NullUUID      `json:"caa_release_mbid"`
	ArtistMbids    []uuid.UUID        `json:"artist_mbids"`
	InsertedAt     pgtype.Timestamptz `json:"inserted_at"`
}

type ListenbrainzSetting struct {
	Singleton           bool               `json:"singleton"`
	BaseUrl             string             `json:"base_url"`
	LabsUrl             string             `json:"labs_url"`
	Username            string             `json:"username"`
	UserToken           pgtype.Text        `json:"user_token"`
	SimilarityAlgorithm string             `json:"similarity_algorithm"`
	Enabled             bool               `json:"enabled"`
	ConnectionStatus    string             `json:"connection_status"`
	ConnectionError     pgtype.Text        `json:"connection_error"`
	ConnectionDetail    pgtype.Text        `json:"connection_detail"`
	LastCheckedAt       pgtype.Timestamptz `json:"last_checked_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type MetadataSource struct {
	ID         uuid.UUID          `json:"id"`
	EntityType string             `json:"entity_type"`
	EntityID   uuid.UUID          `json:"entity_id"`
	Provider   string             `json:"provider"`
	ExternalID string             `json:"external_id"`
	Metadata   []byte             `json:"metadata"`
	FetchedAt  pgtype.Timestamptz `json:"fetched_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type NavidromePlaylistSnapshot struct {
	PlaylistID          uuid.UUID          `json:"playlist_id"`
	NavidromePlaylistID string             `json:"navidrome_playlist_id"`
	Adopted             bool               `json:"adopted"`
	PushedAt            pgtype.Timestamptz `json:"pushed_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type NavidromePlaylistSnapshotTrack struct {
	PlaylistID      uuid.UUID          `json:"playlist_id"`
	Position        int32              `json:"position"`
	NavidromeSongID string             `json:"navidrome_song_id"`
	LibraryPath     string             `json:"library_path"`
	LibraryFileID   uuid.NullUUID      `json:"library_file_id"`
	PlaylistEntryID uuid.NullUUID      `json:"playlist_entry_id"`
	PushedAt        pgtype.Timestamptz `json:"pushed_at"`
}

type NavidromeSetting struct {
	Singleton        bool               `json:"singleton"`
	BaseUrl          string             `json:"base_url"`
	Username         string             `json:"username"`
	Password         string             `json:"password"`
	Enabled          bool               `json:"enabled"`
	ConnectionStatus string             `json:"connection_status"`
	ConnectionError  pgtype.Text        `json:"connection_error"`
	ConnectionDetail pgtype.Text        `json:"connection_detail"`
	LastCheckedAt    pgtype.Timestamptz `json:"last_checked_at"`
	LastNotifiedAt   pgtype.Timestamptz `json:"last_notified_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type NewReleasePlaylistMember struct {
	LibraryFileID   uuid.UUID          `json:"library_file_id"`
	PlaylistEntryID uuid.NullUUID      `json:"playlist_entry_id"`
	AlbumID         uuid.NullUUID      `json:"album_id"`
	ReleasedOn      pgtype.Date        `json:"released_on"`
	AddedAt         pgtype.Timestamptz `json:"added_at"`
	WithdrawnAt     pgtype.Timestamptz `json:"withdrawn_at"`
}

type NewReleasesPlaylistSetting struct {
	Singleton  bool               `json:"singleton"`
	Enabled    bool               `json:"enabled"`
	WindowDays int32              `json:"window_days"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type NotificationSetting struct {
	Singleton        bool               `json:"singleton"`
	Kind             string             `json:"kind"`
	Endpoint         string             `json:"endpoint"`
	Token            pgtype.Text        `json:"token"`
	Enabled          bool               `json:"enabled"`
	ConnectionStatus string             `json:"connection_status"`
	ConnectionError  pgtype.Text        `json:"connection_error"`
	LastCheckedAt    pgtype.Timestamptz `json:"last_checked_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type PeerChallenge struct {
	ID        uuid.UUID          `json:"id"`
	Username  string             `json:"username"`
	Challenge string             `json:"challenge"`
	Reply     pgtype.Text        `json:"reply"`
	SentAt    pgtype.Timestamptz `json:"sent_at"`
	Outcome   string             `json:"outcome"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Playlist struct {
	ID             uuid.UUID          `json:"id"`
	Source         string             `json:"source"`
	SourceID       pgtype.Text        `json:"source_id"`
	SourceRevision pgtype.Text        `json:"source_revision"`
	Name           string             `json:"name"`
	Description    string             `json:"description"`
	OwnerName      string             `json:"owner_name"`
	TrackCount     int32              `json:"track_count"`
	ImportedAt     pgtype.Timestamptz `json:"imported_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type PlaylistEntry struct {
	ID                 uuid.UUID          `json:"id"`
	PlaylistID         uuid.UUID          `json:"playlist_id"`
	Position           int32              `json:"position"`
	SourceTrackID      pgtype.Text        `json:"source_track_id"`
	EntryArtist        string             `json:"entry_artist"`
	EntryTitle         string             `json:"entry_title"`
	EntryAlbum         string             `json:"entry_album"`
	EntryDurationMs    pgtype.Int4        `json:"entry_duration_ms"`
	EntryIsrc          pgtype.Text        `json:"entry_isrc"`
	OwnedLibraryFileID uuid.NullUUID      `json:"owned_library_file_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	EntryExplicit      pgtype.Bool        `json:"entry_explicit"`
}

type PlaylistEntryTarget struct {
	PlaylistEntryID     uuid.UUID          `json:"playlist_entry_id"`
	AcquisitionTargetID uuid.UUID          `json:"acquisition_target_id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type RecommendationCandidate struct {
	Source                    string             `json:"source"`
	MusicbrainzRecordingID    uuid.UUID          `json:"musicbrainz_recording_id"`
	MusicbrainzReleaseGroupID uuid.UUID          `json:"musicbrainz_release_group_id"`
	MusicbrainzArtistIds      []uuid.UUID        `json:"musicbrainz_artist_ids"`
	RecordingTitle            string             `json:"recording_title"`
	ReleaseTitle              string             `json:"release_title"`
	ArtistName                string             `json:"artist_name"`
	Rank                      int32              `json:"rank"`
	SourceScore               pgtype.Float8      `json:"source_score"`
	ReasonCodes               []string           `json:"reason_codes"`
	ReasonContext             []byte             `json:"reason_context"`
	FetchedAt                 pgtype.Timestamptz `json:"fetched_at"`
}

type RecommendationDismissal struct {
	SubjectType   string             `json:"subject_type"`
	MusicbrainzID uuid.UUID          `json:"musicbrainz_id"`
	DismissedAt   pgtype.Timestamptz `json:"dismissed_at"`
}

type RecommendationFeedback struct {
	ID                        uuid.UUID          `json:"id"`
	Source                    string             `json:"source"`
	MusicbrainzRecordingID    uuid.UUID          `json:"musicbrainz_recording_id"`
	MusicbrainzReleaseGroupID uuid.UUID          `json:"musicbrainz_release_group_id"`
	MusicbrainzArtistIds      []uuid.UUID        `json:"musicbrainz_artist_ids"`
	Signal                    string             `json:"signal"`
	ReasonCodes               []string           `json:"reason_codes"`
	ReasonContext             []byte             `json:"reason_context"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
}

type RecommendationImpression struct {
	MusicbrainzRecordingID uuid.UUID          `json:"musicbrainz_recording_id"`
	IgnoredImpressions     int32              `json:"ignored_impressions"`
	LastShownAt            pgtype.Timestamptz `json:"last_shown_at"`
	SuppressedUntil        pgtype.Timestamptz `json:"suppressed_until"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type RecommendationSnapshot struct {
	Source           string             `json:"source"`
	SourceSnapshotID pgtype.Text        `json:"source_snapshot_id"`
	SourceSnapshotAt pgtype.Timestamptz `json:"source_snapshot_at"`
	Status           string             `json:"status"`
	Detail           string             `json:"detail"`
	FetchedAt        pgtype.Timestamptz `json:"fetched_at"`
}

type RecommendationUnkept struct {
	MusicbrainzRecordingID uuid.UUID          `json:"musicbrainz_recording_id"`
	UnkeptAt               pgtype.Timestamptz `json:"unkept_at"`
	SuppressedUntil        pgtype.Timestamptz `json:"suppressed_until"`
	Occurrences            int32              `json:"occurrences"`
	RunID                  uuid.NullUUID      `json:"run_id"`
}

type RecordingAlias struct {
	RetiredID   uuid.UUID          `json:"retired_id"`
	SurvivingID uuid.UUID          `json:"surviving_id"`
	ObservedAt  pgtype.Timestamptz `json:"observed_at"`
}

type ReleaseCoverArt struct {
	AlbumID     uuid.UUID          `json:"album_id"`
	Image       []byte             `json:"image"`
	ContentType string             `json:"content_type"`
	Source      string             `json:"source"`
	FetchedAt   pgtype.Timestamptz `json:"fetched_at"`
}

type ReleaseEdition struct {
	ID                    uuid.UUID          `json:"id"`
	AlbumID               uuid.UUID          `json:"album_id"`
	MusicbrainzReleaseID  uuid.UUID          `json:"musicbrainz_release_id"`
	Title                 string             `json:"title"`
	Status                pgtype.Text        `json:"status"`
	Country               pgtype.Text        `json:"country"`
	Barcode               pgtype.Text        `json:"barcode"`
	ReleaseDate           pgtype.Text        `json:"release_date"`
	MediaCount            int32              `json:"media_count"`
	TrackCount            int32              `json:"track_count"`
	SelectedAutomatically bool               `json:"selected_automatically"`
	SelectionReason       string             `json:"selection_reason"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type SlskdSetting struct {
	Singleton            bool               `json:"singleton"`
	BaseUrl              string             `json:"base_url"`
	ApiKey               string             `json:"api_key"`
	Enabled              bool               `json:"enabled"`
	SearchTimeoutSeconds int32              `json:"search_timeout_seconds"`
	ConnectionStatus     string             `json:"connection_status"`
	ConnectionError      pgtype.Text        `json:"connection_error"`
	ConnectionDetail     pgtype.Text        `json:"connection_detail"`
	LastCheckedAt        pgtype.Timestamptz `json:"last_checked_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	LoggedOutSince       pgtype.Timestamptz `json:"logged_out_since"`
}

type SourcePreference struct {
	Singleton             bool               `json:"singleton"`
	PreferredFormats      []string           `json:"preferred_formats"`
	UnacceptableFormats   []string           `json:"unacceptable_formats"`
	MinimumBitrate        int32              `json:"minimum_bitrate"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	FormatMinimumBitrates []byte             `json:"format_minimum_bitrates"`
}

type SourceSearch struct {
	ID                uuid.UUID          `json:"id"`
	RunID             uuid.UUID          `json:"run_id"`
	AlbumID           uuid.UUID          `json:"album_id"`
	Status            string             `json:"status"`
	Query             string             `json:"query"`
	Candidates        []byte             `json:"candidates"`
	Error             pgtype.Text        `json:"error"`
	RequestedAt       pgtype.Timestamptz `json:"requested_at"`
	SearchedAt        pgtype.Timestamptz `json:"searched_at"`
	AutoRequest       bool               `json:"auto_request"`
	AutoRequestedAt   pgtype.Timestamptz `json:"auto_requested_at"`
	RefusedCandidates []byte             `json:"refused_candidates"`
}

type SpotifySetting struct {
	Singleton        bool               `json:"singleton"`
	ClientID         string             `json:"client_id"`
	ClientSecret     string             `json:"client_secret"`
	RefreshToken     pgtype.Text        `json:"refresh_token"`
	AccountName      pgtype.Text        `json:"account_name"`
	ConnectionStatus string             `json:"connection_status"`
	ConnectionError  pgtype.Text        `json:"connection_error"`
	LastCheckedAt    pgtype.Timestamptz `json:"last_checked_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Track struct {
	ID                     uuid.UUID          `json:"id"`
	AlbumID                uuid.UUID          `json:"album_id"`
	MusicbrainzRecordingID uuid.NullUUID      `json:"musicbrainz_recording_id"`
	Title                  string             `json:"title"`
	DiscNumber             int32              `json:"disc_number"`
	TrackNumber            pgtype.Int4        `json:"track_number"`
	DurationMs             pgtype.Int4        `json:"duration_ms"`
	Isrc                   pgtype.Text        `json:"isrc"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type TrackArtistCredit struct {
	TrackID             uuid.UUID          `json:"track_id"`
	Position            int32              `json:"position"`
	CreditedName        string             `json:"credited_name"`
	MusicbrainzArtistID uuid.NullUUID      `json:"musicbrainz_artist_id"`
	JoinPhrase          string             `json:"join_phrase"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type TrackMapping struct {
	ID            uuid.UUID          `json:"id"`
	TrackID       uuid.UUID          `json:"track_id"`
	LibraryFileID uuid.UUID          `json:"library_file_id"`
	Method        string             `json:"method"`
	Confidence    pgtype.Float4      `json:"confidence"`
	IsManual      bool               `json:"is_manual"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type UpgradeSetting struct {
	Singleton bool               `json:"singleton"`
	Enabled   bool               `json:"enabled"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type WeeklyLibraryPick struct {
	MusicbrainzRecordingID uuid.UUID          `json:"musicbrainz_recording_id"`
	LibraryFileID          uuid.NullUUID      `json:"library_file_id"`
	RunID                  uuid.NullUUID      `json:"run_id"`
	PickedAt               pgtype.Timestamptz `json:"picked_at"`
}

type WeeklyPlaylistRun struct {
	ID            uuid.UUID          `json:"id"`
	PlaylistID    uuid.NullUUID      `json:"playlist_id"`
	Mode          string             `json:"mode"`
	Status        string             `json:"status"`
	Detail        string             `json:"detail"`
	ChosenCount   int32              `json:"chosen_count"`
	WantedCount   int32              `json:"wanted_count"`
	ArrivedCount  int32              `json:"arrived_count"`
	KeptCount     int32              `json:"kept_count"`
	ExtendedCount int32              `json:"extended_count"`
	LeavingCount  int32              `json:"leaving_count"`
	RemovedCount  int32              `json:"removed_count"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
	LibraryShare  int32              `json:"library_share"`
	OnePerArtist  bool               `json:"one_per_artist"`
	LibraryCount  int32              `json:"library_count"`
	ReplacedCount int32              `json:"replaced_count"`
}

type WeeklyPlaylistSetting struct {
	Singleton    bool               `json:"singleton"`
	Enabled      bool               `json:"enabled"`
	SongsPerWeek int32              `json:"songs_per_week"`
	Mode         string             `json:"mode"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	LibraryShare int32              `json:"library_share"`
	OnePerArtist bool               `json:"one_per_artist"`
}
