// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type PeerChallenge struct {
	ID        uuid.UUID          `json:"id"`
	Username  string             `json:"username"`
	Challenge string             `json:"challenge"`
	Reply     pgtype.Text        `json:"reply"`
	SentAt    pgtype.Timestamptz `json:"sent_at"`
	Outcome   string             `json:"outcome"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RecommendationCandidate struct {
	Source                    string             `json:"source"`
	MusicbrainzRecordingID    uuid.UUID          `json:"musicbrainz_recording_id"`
	MusicbrainzReleaseGroupID uuid.UUID          `json:"musicbrainz_release_group_id"`
	MusicbrainzArtistIds      []uuid.UUID        `json:"musicbrainz_artist_ids"`
	RecordingTitle            string             `json:"recording_title"`
	ReleaseTitle              string             `json:"release_title"`
	ArtistName                string             `json:"artist_name"`
	Rank                      int32              `json:"rank"`
	SourceScore               pgtype.Float8      `json:"source_score"`
	ReasonCodes               []string           `json:"reason_codes"`
	ReasonContext             []byte             `json:"reason_context"`
	FetchedAt                 pgtype.Timestamptz `json:"fetched_at"`
}

type RecommendationDismissal struct {
	SubjectType   string             `json:"subject_type"`
	MusicbrainzID uuid.UUID          `json:"musicbrainz_id"`
	DismissedAt   pgtype.Timestamptz `json:"dismissed_at"`
}

type RecommendationFeedback struct {
	ID                        uuid.UUID          `json:"id"`
	Source                    string             `json:"source"`
	MusicbrainzRecordingID    uuid.UUID          `json:"musicbrainz_recording_id"`
	MusicbrainzReleaseGroupID uuid.UUID          `json:"musicbrainz_release_group_id"`
	MusicbrainzArtistIds      []uuid.UUID        `json:"musicbrainz_artist_ids"`
	Signal                    string             `json:"signal"`
	ReasonCodes               []string           `json:"reason_codes"`
	ReasonContext             []byte             `json:"reason_context"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
}

type RecommendationImpression struct {
	MusicbrainzRecordingID uuid.UUID          `json:"musicbrainz_recording_id"`
	IgnoredImpressions     int32              `json:"ignored_impressions"`
	LastShownAt            pgtype.Timestamptz `json:"last_shown_at"`
	SuppressedUntil        pgtype.Timestamptz `json:"suppressed_until"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type RecommendationSnapshot struct {
	Source           string             `json:"source"`
	SourceSnapshotID pgtype.Text        `json:"source_snapshot_id"`
	SourceSnapshotAt pgtype.Timestamptz `json:"source_snapshot_at"`
	Status           string             `json:"status"`
	Detail           string             `json:"detail"`
	FetchedAt        pgtype.Timestamptz `json:"fetched_at"`
}
