// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: peer_challenges.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const failedDownloadRequestsForPeer = `-- name: FailedDownloadRequestsForPeer :many
SELECT id
FROM download_requests
WHERE provider = $1
  AND source_username = $2
  AND status = 'failed'
  AND updated_at >= $3
ORDER BY updated_at DESC
`

type FailedDownloadRequestsForPeerParams struct {
	Provider string             `json:"provider"`
	Username string             `json:"username"`
	Since    pgtype.Timestamptz `json:"since"`
}

// The requests to this peer that failed recently, so the files it refused can
// be asked for again once it has been answered.
func (q *Queries) FailedDownloadRequestsForPeer(ctx context.Context, arg FailedDownloadRequestsForPeerParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, failedDownloadRequestsForPeer, arg.Provider, arg.Username, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const forgetPeerQuestions = `-- name: ForgetPeerQuestions :exec
DELETE FROM peer_challenges
WHERE username = $1
  AND outcome = 'unanswered'
`

// Drop what this peer said before, so one peer is one line on the Downloads
// page. Only the messages nobody could read: what was sent stays as the record
// the once-a-day rule and the daily cap are counted from.
func (q *Queries) ForgetPeerQuestions(ctx context.Context, username string) error {
	_, err := q.db.Exec(ctx, forgetPeerQuestions, username)
	return err
}

const peerChallengeAnswered = `-- name: PeerChallengeAnswered :one
SELECT EXISTS (
    SELECT 1
    FROM peer_challenges
    WHERE username = $1
      AND challenge = $2
      AND outcome <> 'unanswered'
      AND sent_at >= $3
) AS answered
`

type PeerChallengeAnsweredParams struct {
	Username  string             `json:"username"`
	Challenge string             `json:"challenge"`
	Since     pgtype.Timestamptz `json:"since"`
}

// Whether this peer has already been sent something for this exact question
// since a moment. A peer that changes a word changes the question, and gets one
// answer for the new one.
func (q *Queries) PeerChallengeAnswered(ctx context.Context, arg PeerChallengeAnsweredParams) (bool, error) {
	row := q.db.QueryRow(ctx, peerChallengeAnswered, arg.Username, arg.Challenge, arg.Since)
	var answered bool
	err := row.Scan(&answered)
	return answered, err
}

const peerChallengeSeen = `-- name: PeerChallengeSeen :one
SELECT EXISTS (
    SELECT 1
    FROM peer_challenges
    WHERE username = $1
      AND challenge = $2
) AS seen
`

type PeerChallengeSeenParams struct {
	Username  string `json:"username"`
	Challenge string `json:"challenge"`
}

// Whether this exact message has been recorded at all. The peers that challenge
// send the same lines every time a transfer is requested, and one unread
// message is one row rather than one a day.
func (q *Queries) PeerChallengeSeen(ctx context.Context, arg PeerChallengeSeenParams) (bool, error) {
	row := q.db.QueryRow(ctx, peerChallengeSeen, arg.Username, arg.Challenge)
	var seen bool
	err := row.Scan(&seen)
	return seen, err
}

const peerRepliesSince = `-- name: PeerRepliesSince :one
SELECT count(*)::bigint AS replies
FROM peer_challenges
WHERE sent_at >= $1
`

// How many messages have been sent to peers since a moment, whoever sent them.
// The Soulseek server bans this account for flooding private chat, and this is
// what the daily cap is counted from.
func (q *Queries) PeerRepliesSince(ctx context.Context, since pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, peerRepliesSince, since)
	var replies int64
	err := row.Scan(&replies)
	return replies, err
}

const peersAwaitingTransfers = `-- name: PeersAwaitingTransfers :many
SELECT
    source_username,
    bool_or(status IN ('requested', 'started')) AS open
FROM download_requests
WHERE provider = $1
  AND (
      status IN ('requested', 'started')
      OR (status = 'failed' AND updated_at >= $2)
  )
GROUP BY source_username
ORDER BY source_username
`

type PeersAwaitingTransfersParams struct {
	Provider string             `json:"provider"`
	Since    pgtype.Timestamptz `json:"since"`
}

type PeersAwaitingTransfersRow struct {
	SourceUsername string `json:"source_username"`
	Open           bool   `json:"open"`
}

// The peers worth reading private chat from: the ones with a request still
// open, and the ones whose request failed recently enough that a challenge is
// what it failed on. Open says whether anything is still waiting, which is what
// decides whether to look again in a minute.
func (q *Queries) PeersAwaitingTransfers(ctx context.Context, arg PeersAwaitingTransfersParams) ([]PeersAwaitingTransfersRow, error) {
	rows, err := q.db.Query(ctx, peersAwaitingTransfers, arg.Provider, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PeersAwaitingTransfersRow{}
	for rows.Next() {
		var i PeersAwaitingTransfersRow
		if err := rows.Scan(&i.SourceUsername, &i.Open); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordPeerChallenge = `-- name: RecordPeerChallenge :one
INSERT INTO peer_challenges (username, challenge, reply, sent_at, outcome)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, username, challenge, reply, sent_at, outcome, created_at
`

type RecordPeerChallengeParams struct {
	Username  string             `json:"username"`
	Challenge string             `json:"challenge"`
	Reply     pgtype.Text        `json:"reply"`
	SentAt    pgtype.Timestamptz `json:"sent_at"`
	Outcome   string             `json:"outcome"`
}

// Keep what a peer asked and what was sent back. A row with no reply is a
// message nobody here could read; it is what the Downloads page shows and what
// a person answers by hand.
func (q *Queries) RecordPeerChallenge(ctx context.Context, arg RecordPeerChallengeParams) (PeerChallenge, error) {
	row := q.db.QueryRow(ctx, recordPeerChallenge,
		arg.Username,
		arg.Challenge,
		arg.Reply,
		arg.SentAt,
		arg.Outcome,
	)
	var i PeerChallenge
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Challenge,
		&i.Reply,
		&i.SentAt,
		&i.Outcome,
		&i.CreatedAt,
	)
	return i, err
}

const unansweredPeerChallenges = `-- name: UnansweredPeerChallenges :many
SELECT DISTINCT ON (username) id, username, challenge, created_at
FROM peer_challenges
WHERE username = ANY($1::text[])
  AND outcome = 'unanswered'
  AND NOT EXISTS (
      SELECT 1
      FROM peer_challenges answered
      WHERE answered.username = peer_challenges.username
        AND answered.outcome <> 'unanswered'
        AND answered.created_at > peer_challenges.created_at
  )
ORDER BY username, created_at DESC
`

type UnansweredPeerChallengesRow struct {
	ID        uuid.UUID          `json:"id"`
	Username  string             `json:"username"`
	Challenge string             `json:"challenge"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// The last thing each of these peers said that could not be read, unless
// something has been sent to that peer since. One line per peer: the Downloads
// page shows it beside the request that peer is holding up.
func (q *Queries) UnansweredPeerChallenges(ctx context.Context, usernames []string) ([]UnansweredPeerChallengesRow, error) {
	rows, err := q.db.Query(ctx, unansweredPeerChallenges, usernames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UnansweredPeerChallengesRow{}
	for rows.Next() {
		var i UnansweredPeerChallengesRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Challenge,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
