// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recommendations.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteRecommendationCandidates = `-- name: DeleteRecommendationCandidates :exec
DELETE FROM recommendation_candidates WHERE source = $1
`

func (q *Queries) DeleteRecommendationCandidates(ctx context.Context, source string) error {
	_, err := q.db.Exec(ctx, deleteRecommendationCandidates, source)
	return err
}

const deleteRecommendationFeedback = `-- name: DeleteRecommendationFeedback :exec
DELETE FROM recommendation_feedback
WHERE source = $1
`

func (q *Queries) DeleteRecommendationFeedback(ctx context.Context, source string) error {
	_, err := q.db.Exec(ctx, deleteRecommendationFeedback, source)
	return err
}

const insertRecommendationCandidate = `-- name: InsertRecommendationCandidate :one
INSERT INTO recommendation_candidates (
    source,
    musicbrainz_recording_id,
    musicbrainz_release_group_id,
    musicbrainz_artist_ids,
    recording_title,
    release_title,
    artist_name,
    rank,
    source_score,
    reason_codes,
    reason_context,
    fetched_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12
)
RETURNING source, musicbrainz_recording_id, musicbrainz_release_group_id, musicbrainz_artist_ids, recording_title, release_title, artist_name, rank, source_score, reason_codes, reason_context, fetched_at
`

type InsertRecommendationCandidateParams struct {
	Source                    string             `json:"source"`
	MusicbrainzRecordingID    uuid.UUID          `json:"musicbrainz_recording_id"`
	MusicbrainzReleaseGroupID uuid.UUID          `json:"musicbrainz_release_group_id"`
	MusicbrainzArtistIds      []uuid.UUID        `json:"musicbrainz_artist_ids"`
	RecordingTitle            string             `json:"recording_title"`
	ReleaseTitle              string             `json:"release_title"`
	ArtistName                string             `json:"artist_name"`
	Rank                      int32              `json:"rank"`
	SourceScore               pgtype.Float8      `json:"source_score"`
	ReasonCodes               []string           `json:"reason_codes"`
	ReasonContext             []byte             `json:"reason_context"`
	FetchedAt                 pgtype.Timestamptz `json:"fetched_at"`
}

func (q *Queries) InsertRecommendationCandidate(ctx context.Context, arg InsertRecommendationCandidateParams) (RecommendationCandidate, error) {
	row := q.db.QueryRow(ctx, insertRecommendationCandidate,
		arg.Source,
		arg.MusicbrainzRecordingID,
		arg.MusicbrainzReleaseGroupID,
		arg.MusicbrainzArtistIds,
		arg.RecordingTitle,
		arg.ReleaseTitle,
		arg.ArtistName,
		arg.Rank,
		arg.SourceScore,
		arg.ReasonCodes,
		arg.ReasonContext,
		arg.FetchedAt,
	)
	var i RecommendationCandidate
	err := row.Scan(
		&i.Source,
		&i.MusicbrainzRecordingID,
		&i.MusicbrainzReleaseGroupID,
		&i.MusicbrainzArtistIds,
		&i.RecordingTitle,
		&i.ReleaseTitle,
		&i.ArtistName,
		&i.Rank,
		&i.SourceScore,
		&i.ReasonCodes,
		&i.ReasonContext,
		&i.FetchedAt,
	)
	return i, err
}

const listRecommendationCandidateFacts = `-- name: ListRecommendationCandidateFacts :many
WITH listed AS (
    SELECT
        candidates.source, candidates.musicbrainz_recording_id, candidates.musicbrainz_release_group_id, candidates.musicbrainz_artist_ids, candidates.recording_title, candidates.release_title, candidates.artist_name, candidates.rank, candidates.source_score, candidates.reason_codes, candidates.reason_context, candidates.fetched_at,
        snapshots.source_snapshot_id,
        snapshots.source_snapshot_at,
        snapshots.status AS snapshot_status,
        snapshots.detail AS snapshot_detail,
        snapshots.fetched_at AS snapshot_fetched_at
    FROM recommendation_candidates AS candidates
    JOIN recommendation_snapshots AS snapshots ON snapshots.source = candidates.source
    WHERE candidates.source = $2
),
owned_recordings AS (
    SELECT library_file_identities.musicbrainz_recording_id AS musicbrainz_id
    FROM library_file_identities
    JOIN library_files ON library_files.id = library_file_identities.library_file_id
    WHERE library_files.missing_at IS NULL
      AND library_file_identities.musicbrainz_recording_id
              IN (SELECT musicbrainz_recording_id FROM listed)
    UNION
    SELECT tracks.musicbrainz_recording_id
    FROM tracks
    JOIN track_mappings ON track_mappings.track_id = tracks.id
    JOIN library_files ON library_files.id = track_mappings.library_file_id
    WHERE library_files.missing_at IS NULL
      AND tracks.musicbrainz_recording_id
              IN (SELECT musicbrainz_recording_id FROM listed)
),
owned_release_groups AS (
    SELECT library_file_identities.musicbrainz_release_group_id AS musicbrainz_id
    FROM library_file_identities
    JOIN library_files ON library_files.id = library_file_identities.library_file_id
    WHERE library_files.missing_at IS NULL
      AND library_file_identities.musicbrainz_release_group_id
              IN (SELECT musicbrainz_release_group_id FROM listed)
    UNION
    SELECT albums.musicbrainz_release_group_id
    FROM albums
    JOIN tracks ON tracks.album_id = albums.id
    JOIN track_mappings ON track_mappings.track_id = tracks.id
    JOIN library_files ON library_files.id = track_mappings.library_file_id
    WHERE library_files.missing_at IS NULL
      AND albums.musicbrainz_release_group_id
              IN (SELECT musicbrainz_release_group_id FROM listed)
)
SELECT
    listed.source, listed.musicbrainz_recording_id, listed.musicbrainz_release_group_id, listed.musicbrainz_artist_ids, listed.recording_title, listed.release_title, listed.artist_name, listed.rank, listed.source_score, listed.reason_codes, listed.reason_context, listed.fetched_at, listed.source_snapshot_id, listed.source_snapshot_at, listed.snapshot_status, listed.snapshot_detail, listed.snapshot_fetched_at,
    (
        listed.musicbrainz_recording_id IN (SELECT musicbrainz_id FROM owned_recordings)
        OR listed.musicbrainz_release_group_id
               IN (SELECT musicbrainz_id FROM owned_release_groups)
    )::boolean AS owned,
    EXISTS (
        SELECT 1
        FROM acquisition_targets
        WHERE acquisition_targets.musicbrainz_recording_id
                = listed.musicbrainz_recording_id
          AND acquisition_targets.status IN (
              'unresolved', 'pending', 'searching', 'awaiting_review'
          )
    )::boolean AS requested,
    -- A want somebody stopped. It is a decision about acquisition, not about
    -- taste, so it is counted apart from a dismissal and read as its own rule:
    -- the only two things this list offers are "find me a copy" and "never
    -- suggest it again", and a reader who already answered the first one has
    -- nothing left here to press (issue #338).
    EXISTS (
        SELECT 1
        FROM acquisition_targets
        WHERE acquisition_targets.musicbrainz_recording_id
                = listed.musicbrainz_recording_id
          AND acquisition_targets.status = 'not_wanted'
    )::boolean AS not_wanted,
    EXISTS (
        SELECT 1
        FROM artists
        WHERE artists.musicbrainz_id = ANY(listed.musicbrainz_artist_ids)
          AND artists.followed_at IS NOT NULL
    )::boolean AS followed_artist,
    -- The same rule again, for a label instead of an artist: the follow feed
    -- already covers this release, so recommending it a second time here is
    -- offering to fetch it twice.
    EXISTS (
        SELECT 1
        FROM label_releases
        JOIN labels ON labels.id = label_releases.label_id
        JOIN albums ON albums.id = label_releases.album_id
        WHERE albums.musicbrainz_release_group_id = listed.musicbrainz_release_group_id
          AND labels.followed_at IS NOT NULL
    )::boolean AS followed_label,
    (
        EXISTS (
            SELECT 1 FROM recommendation_dismissals
            WHERE subject_type = 'recording'
              AND musicbrainz_id = listed.musicbrainz_recording_id
        )
        OR EXISTS (
            SELECT 1 FROM recommendation_dismissals
            WHERE subject_type = 'release_group'
              AND musicbrainz_id = listed.musicbrainz_release_group_id
        )
        OR EXISTS (
            SELECT 1 FROM recommendation_dismissals
            WHERE subject_type = 'artist'
              AND musicbrainz_id = ANY(listed.musicbrainz_artist_ids)
        )
    )::boolean AS dismissed,
    EXISTS (
        SELECT 1
        FROM recommendation_impressions
        WHERE recommendation_impressions.musicbrainz_recording_id
                = listed.musicbrainz_recording_id
          AND recommendation_impressions.suppressed_until > $1
    )::boolean AS impression_fatigue,
    -- The sixth rule. The weekly playlist obtained this recording, the user had
    -- it on their disc for a week, and nothing said they wanted to keep it, so
    -- it was removed again (ADR 0021). Offering it back the following week would
    -- buy it a second time. The window is written by the weekly refresh and
    -- expires on its own, because a week of not listening is not the statement
    -- "never suggest this" — that statement is a dismissal, and the reader makes
    -- it themselves.
    EXISTS (
        SELECT 1
        FROM recommendation_unkept
        WHERE recommendation_unkept.musicbrainz_recording_id
                = listed.musicbrainz_recording_id
          AND recommendation_unkept.suppressed_until > $1
    )::boolean AS unkept
FROM listed
ORDER BY listed.rank
`

type ListRecommendationCandidateFactsParams struct {
	ObservedAt pgtype.Timestamptz `json:"observed_at"`
	Source     string             `json:"source"`
}

type ListRecommendationCandidateFactsRow struct {
	Source                    string             `json:"source"`
	MusicbrainzRecordingID    uuid.UUID          `json:"musicbrainz_recording_id"`
	MusicbrainzReleaseGroupID uuid.UUID          `json:"musicbrainz_release_group_id"`
	MusicbrainzArtistIds      []uuid.UUID        `json:"musicbrainz_artist_ids"`
	RecordingTitle            string             `json:"recording_title"`
	ReleaseTitle              string             `json:"release_title"`
	ArtistName                string             `json:"artist_name"`
	Rank                      int32              `json:"rank"`
	SourceScore               pgtype.Float8      `json:"source_score"`
	ReasonCodes               []string           `json:"reason_codes"`
	ReasonContext             []byte             `json:"reason_context"`
	FetchedAt                 pgtype.Timestamptz `json:"fetched_at"`
	SourceSnapshotID          pgtype.Text        `json:"source_snapshot_id"`
	SourceSnapshotAt          pgtype.Timestamptz `json:"source_snapshot_at"`
	SnapshotStatus            string             `json:"snapshot_status"`
	SnapshotDetail            string             `json:"snapshot_detail"`
	SnapshotFetchedAt         pgtype.Timestamptz `json:"snapshot_fetched_at"`
	Owned                     bool               `json:"owned"`
	Requested                 bool               `json:"requested"`
	NotWanted                 bool               `json:"not_wanted"`
	FollowedArtist            bool               `json:"followed_artist"`
	FollowedLabel             bool               `json:"followed_label"`
	Dismissed                 bool               `json:"dismissed"`
	ImpressionFatigue         bool               `json:"impression_fatigue"`
	Unkept                    bool               `json:"unkept"`
}

// These are the inputs to the pure suppression decision: one per rule, and two
// for the second, which asks whether the reader has already answered about
// acquiring this recording — by asking for it, or by stopping. They are read
// from current local state every time the list is asked for; provider rows are
// never deleted or annotated merely because one input currently suppresses.
//
// The first rule, `owned`, asks whether the library already holds the music,
// and it can be answered four ways: the file's proven identity names the
// recording or its release group, or the track the file is mapped to names the
// recording, or that track's album names the release group.
//
// Those four used to be one EXISTS with an OR across three tables, written
// beside the candidate it was about. A subquery in the select list is run once
// per row and is never turned into a join, so every suggestion walked the whole
// library: 1298 suggestions against 30000 files measured 79 seconds, with the
// walk repeated 1298 times (issue #331).
//
// The four answers are collected first instead, and only for the identifiers
// this list actually carries. Each set is then at most as large as the list, so
// what a read costs follows the length of the list and no longer the size of
// the collection: the same 1298 against the same 30000 measured 36 milliseconds.
// Restricting each set to the list is what keeps it small enough to hash, which
// is what stops the walk coming back on a larger library.
// A file that has gone missing proves nothing, here as everywhere else.
func (q *Queries) ListRecommendationCandidateFacts(ctx context.Context, arg ListRecommendationCandidateFactsParams) ([]ListRecommendationCandidateFactsRow, error) {
	rows, err := q.db.Query(ctx, listRecommendationCandidateFacts, arg.ObservedAt, arg.Source)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecommendationCandidateFactsRow{}
	for rows.Next() {
		var i ListRecommendationCandidateFactsRow
		if err := rows.Scan(
			&i.Source,
			&i.MusicbrainzRecordingID,
			&i.MusicbrainzReleaseGroupID,
			&i.MusicbrainzArtistIds,
			&i.RecordingTitle,
			&i.ReleaseTitle,
			&i.ArtistName,
			&i.Rank,
			&i.SourceScore,
			&i.ReasonCodes,
			&i.ReasonContext,
			&i.FetchedAt,
			&i.SourceSnapshotID,
			&i.SourceSnapshotAt,
			&i.SnapshotStatus,
			&i.SnapshotDetail,
			&i.SnapshotFetchedAt,
			&i.Owned,
			&i.Requested,
			&i.NotWanted,
			&i.FollowedArtist,
			&i.FollowedLabel,
			&i.Dismissed,
			&i.ImpressionFatigue,
			&i.Unkept,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecommendationFeedback = `-- name: ListRecommendationFeedback :many
SELECT id, source, musicbrainz_recording_id, musicbrainz_release_group_id, musicbrainz_artist_ids, signal, reason_codes, reason_context, created_at
FROM recommendation_feedback
WHERE source = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListRecommendationFeedback(ctx context.Context, source string) ([]RecommendationFeedback, error) {
	rows, err := q.db.Query(ctx, listRecommendationFeedback, source)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecommendationFeedback{}
	for rows.Next() {
		var i RecommendationFeedback
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.MusicbrainzRecordingID,
			&i.MusicbrainzReleaseGroupID,
			&i.MusicbrainzArtistIds,
			&i.Signal,
			&i.ReasonCodes,
			&i.ReasonContext,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listedRecommendationRecordings = `-- name: ListedRecommendationRecordings :many
SELECT DISTINCT musicbrainz_recording_id
FROM recommendation_candidates
WHERE musicbrainz_recording_id = ANY($1::uuid[])
`

// Which of these recordings a stored list actually offers.
//
// The fatigue count may only be written about a row that existed to be shown,
// and the route that writes it takes any UUID a caller sends. No source is
// named because impressions are not: one recording has one fatigue cycle,
// whichever list offered it.
func (q *Queries) ListedRecommendationRecordings(ctx context.Context, musicbrainzRecordingIds []uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listedRecommendationRecordings, musicbrainzRecordingIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var musicbrainz_recording_id uuid.UUID
		if err := rows.Scan(&musicbrainz_recording_id); err != nil {
			return nil, err
		}
		items = append(items, musicbrainz_recording_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordRecommendationFeedback = `-- name: RecordRecommendationFeedback :one
INSERT INTO recommendation_feedback (
    source,
    musicbrainz_recording_id,
    musicbrainz_release_group_id,
    musicbrainz_artist_ids,
    signal,
    reason_codes,
    reason_context
)
SELECT
    candidates.source,
    candidates.musicbrainz_recording_id,
    candidates.musicbrainz_release_group_id,
    candidates.musicbrainz_artist_ids,
    $1::text,
    candidates.reason_codes,
    candidates.reason_context
FROM recommendation_candidates AS candidates
WHERE candidates.source = $2
  AND candidates.musicbrainz_recording_id = $3
RETURNING id, source, musicbrainz_recording_id, musicbrainz_release_group_id, musicbrainz_artist_ids, signal, reason_codes, reason_context, created_at
`

type RecordRecommendationFeedbackParams struct {
	Signal                 string    `json:"signal"`
	Source                 string    `json:"source"`
	MusicbrainzRecordingID uuid.UUID `json:"musicbrainz_recording_id"`
}

// The candidate supplies all context. A missing current row means the source
// replaced the suggestion before this press arrived, so no feedback is stored.
func (q *Queries) RecordRecommendationFeedback(ctx context.Context, arg RecordRecommendationFeedbackParams) (RecommendationFeedback, error) {
	row := q.db.QueryRow(ctx, recordRecommendationFeedback, arg.Signal, arg.Source, arg.MusicbrainzRecordingID)
	var i RecommendationFeedback
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.MusicbrainzRecordingID,
		&i.MusicbrainzReleaseGroupID,
		&i.MusicbrainzArtistIds,
		&i.Signal,
		&i.ReasonCodes,
		&i.ReasonContext,
		&i.CreatedAt,
	)
	return i, err
}

const recordRecommendationImpression = `-- name: RecordRecommendationImpression :one
INSERT INTO recommendation_impressions (
    musicbrainz_recording_id,
    ignored_impressions,
    last_shown_at,
    suppressed_until,
    created_at,
    updated_at
)
VALUES (
    $1,
    1,
    $2,
    CASE WHEN $3::integer <= 1
         THEN $2::timestamptz
              + $4::bigint * interval '1 microsecond'
    END,
    $2,
    $2
)
ON CONFLICT (musicbrainz_recording_id) DO UPDATE SET
    ignored_impressions = CASE
        WHEN (recommendation_impressions.suppressed_until IS NULL
              OR recommendation_impressions.suppressed_until <= $2)
         AND recommendation_impressions.last_shown_at
                <= $2::timestamptz
                   - $5::bigint * interval '1 microsecond'
            THEN CASE
                WHEN recommendation_impressions.suppressed_until IS NOT NULL
                    THEN 1
                ELSE recommendation_impressions.ignored_impressions + 1
            END
        ELSE recommendation_impressions.ignored_impressions
    END,
    last_shown_at = CASE
        WHEN (recommendation_impressions.suppressed_until IS NULL
              OR recommendation_impressions.suppressed_until <= $2)
         AND recommendation_impressions.last_shown_at
                <= $2::timestamptz
                   - $5::bigint * interval '1 microsecond'
            THEN $2
        ELSE recommendation_impressions.last_shown_at
    END,
    suppressed_until = CASE
        WHEN NOT (
            (recommendation_impressions.suppressed_until IS NULL
             OR recommendation_impressions.suppressed_until <= $2)
            AND recommendation_impressions.last_shown_at
                  <= $2::timestamptz
                     - $5::bigint * interval '1 microsecond'
        ) THEN recommendation_impressions.suppressed_until
        WHEN recommendation_impressions.suppressed_until IS NOT NULL THEN NULL
        WHEN recommendation_impressions.ignored_impressions + 1 >= $3::integer
            THEN $2::timestamptz
                 + $4::bigint * interval '1 microsecond'
        ELSE NULL
    END,
    updated_at = CASE
        WHEN (recommendation_impressions.suppressed_until IS NULL
              OR recommendation_impressions.suppressed_until <= $2)
         AND recommendation_impressions.last_shown_at
                <= $2::timestamptz
                   - $5::bigint * interval '1 microsecond'
            THEN $2
        ELSE recommendation_impressions.updated_at
    END
RETURNING musicbrainz_recording_id, ignored_impressions, last_shown_at, suppressed_until, created_at, updated_at
`

type RecordRecommendationImpressionParams struct {
	MusicbrainzRecordingID  uuid.UUID          `json:"musicbrainz_recording_id"`
	ObservedAt              pgtype.Timestamptz `json:"observed_at"`
	Threshold               int32              `json:"threshold"`
	SuppressionMicroseconds int64              `json:"suppression_microseconds"`
	MinimumGapMicroseconds  int64              `json:"minimum_gap_microseconds"`
}

// One row is the whole fatigue cycle. A read inside the minimum interval is a
// no-op; the first showing after an expired suppression starts at one and clears
// that stale window in the same update so the ordering constraint stays true.
func (q *Queries) RecordRecommendationImpression(ctx context.Context, arg RecordRecommendationImpressionParams) (RecommendationImpression, error) {
	row := q.db.QueryRow(ctx, recordRecommendationImpression,
		arg.MusicbrainzRecordingID,
		arg.ObservedAt,
		arg.Threshold,
		arg.SuppressionMicroseconds,
		arg.MinimumGapMicroseconds,
	)
	var i RecommendationImpression
	err := row.Scan(
		&i.MusicbrainzRecordingID,
		&i.IgnoredImpressions,
		&i.LastShownAt,
		&i.SuppressedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRecommendationDismissal = `-- name: UpsertRecommendationDismissal :one
INSERT INTO recommendation_dismissals (subject_type, musicbrainz_id, dismissed_at)
VALUES ($1, $2, $3)
ON CONFLICT (subject_type, musicbrainz_id) DO UPDATE SET
    -- Repeating the same dismissal is the same permanent fact. Keep when the
    -- user first said it rather than making a retry look like a new decision.
    dismissed_at = recommendation_dismissals.dismissed_at
RETURNING subject_type, musicbrainz_id, dismissed_at
`

type UpsertRecommendationDismissalParams struct {
	SubjectType   string             `json:"subject_type"`
	MusicbrainzID uuid.UUID          `json:"musicbrainz_id"`
	DismissedAt   pgtype.Timestamptz `json:"dismissed_at"`
}

func (q *Queries) UpsertRecommendationDismissal(ctx context.Context, arg UpsertRecommendationDismissalParams) (RecommendationDismissal, error) {
	row := q.db.QueryRow(ctx, upsertRecommendationDismissal, arg.SubjectType, arg.MusicbrainzID, arg.DismissedAt)
	var i RecommendationDismissal
	err := row.Scan(&i.SubjectType, &i.MusicbrainzID, &i.DismissedAt)
	return i, err
}

const upsertRecommendationSnapshot = `-- name: UpsertRecommendationSnapshot :one
INSERT INTO recommendation_snapshots (
    source,
    source_snapshot_id,
    source_snapshot_at,
    status,
    detail,
    fetched_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
ON CONFLICT (source) DO UPDATE SET
    source_snapshot_id = excluded.source_snapshot_id,
    source_snapshot_at = excluded.source_snapshot_at,
    status = excluded.status,
    detail = excluded.detail,
    fetched_at = excluded.fetched_at
RETURNING source, source_snapshot_id, source_snapshot_at, status, detail, fetched_at
`

type UpsertRecommendationSnapshotParams struct {
	Source           string             `json:"source"`
	SourceSnapshotID pgtype.Text        `json:"source_snapshot_id"`
	SourceSnapshotAt pgtype.Timestamptz `json:"source_snapshot_at"`
	Status           string             `json:"status"`
	Detail           string             `json:"detail"`
	FetchedAt        pgtype.Timestamptz `json:"fetched_at"`
}

func (q *Queries) UpsertRecommendationSnapshot(ctx context.Context, arg UpsertRecommendationSnapshotParams) (RecommendationSnapshot, error) {
	row := q.db.QueryRow(ctx, upsertRecommendationSnapshot,
		arg.Source,
		arg.SourceSnapshotID,
		arg.SourceSnapshotAt,
		arg.Status,
		arg.Detail,
		arg.FetchedAt,
	)
	var i RecommendationSnapshot
	err := row.Scan(
		&i.Source,
		&i.SourceSnapshotID,
		&i.SourceSnapshotAt,
		&i.Status,
		&i.Detail,
		&i.FetchedAt,
	)
	return i, err
}
